### ISSUE TITLE
SubmitPartial, PoolInfo not found

### ISSUE THREAD

**Issue by lingfan** [Chia-Network/pool-reference#1]
Traceback (most recent call last):
  File "pool_server.py", line 10, in <module>
    from chia.protocols.pool_protocol import SubmitPartial, PoolInfo
ImportError: cannot import name 'SubmitPartial' from 'chia.protocols.pool_protocol' 

![image](https://user-images.githubusercontent.com/455872/118374041-8993b480-b5ec-11eb-99ec-abd265a4d961.png)

**Comment by mariano54** [comment]
This is just a draft, it is not done yet. It does not currently run.

**Comment by navid-kalaei** [comment]
has the this draft been developed based on the internal team discussion and is it SOLID? we want to contribute but are not sure about how much change will be made from your side
