### ISSUE TITLE
`chia plotnft show `Connection error

### ISSUE THREAD

**Issue by qian-fei** [Chia-Network/pool-reference#104]
venv) [root@c7-zfs chia-blockchain]# chia plotnft show
Connection error. Check if the wallet is running at 9256. You can run the wallet via:
	chia start wallet

(venv) [root@c7-zfs chia-blockchain]# curl --insecure --cert /root/chia-blockchain/.chia/testnet7/config/ssl/wallet/private_wallet.crt \
> --key /root/chia-blockchain/.chia/testnet7/config/ssl/wallet/private_wallet.key -d '{"wallet_id": 1}' \
> -H "Content-Type: application/json" -X POST https://localhost:9256/get_wallet_balance | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   258  100   242  100    16   1142     75 --:--:-- --:--:-- --:--:--  1146
{
    "success": true,
    "wallet_balance": {
        "confirmed_wallet_balance": 0,
        "max_send_amount": 0,
        "pending_change": 0,
        "pending_coin_removal_count": 0,
        "spendable_balance": 0,
        "unconfirmed_wallet_balance": 0,
        "unspent_coin_count": 0,
        "wallet_id": 1
    }
}

**Comment by qian-fei** [comment]
Error creating plot NFT: {'error': 'Not enough balance in main wallet to create a managed plotting pool.', 'success': False}

**Comment by vden** [comment]
You need to have at least 1 mojo in your account to create a plotnft. 
On testnet you can obtain it from http://chia-faucet.com/, on mainnet from https://faucet.chia.net/

**Comment by qian-fei** [comment]
tks

**Comment by qian-fei** [comment]
> You need to have at least 1 mojo in your account to create a plotnft.
> On testnet you can obtain it from http://chia-faucet.com/, on mainnet from https://faucet.chia.net/

Late arrival

**Comment by qian-fei** [comment]
> You need to have at least 1 mojo in your account to create a plotnft.
> On testnet you can obtain it from http://chia-faucet.com/, on mainnet from https://faucet.chia.net/

It shows that the acquisition was successful, but it was not received in the account.

**Comment by mariano54** [comment]
Post your address and i'll send you some

**Comment by qian-fei** [comment]
> Post your address and i'll send you some

txch1hs6cw4vtrtha2aea6qzfp3gd5a6y3wj0wv3afpl6pmr2r7t6rstqzefc9q
txch1veffxy894d22xywwjly9esaf6n7hmpduxfn9cpxz0qqn48x5u5hqeyc236
txch1j7g5mzhta5g0cyvgpxsd9m68esggjl2n2q6t6w0enc4lfugy3khstq3vmr

**Comment by qian-fei** [comment]
> Post your address and i'll send you some

Not received

**Comment by FLKaplan20271** [comment]
Has there been any update on this?  I am experiencing the same issue:
xch1wwzl39nh48prdrjlu97leh8hlmvmsx0xth79xc4e9324eu5mexyqzrlhfy
