### ISSUE TITLE
is it important with right farmer_public_key when creating a plot with pool_contract_address?

### ISSUE THREAD

**Issue by rocqina** [Chia-Network/pool-reference#108]
If I do not set farmer_public_key when creating a plot with pool_contract_address, it will use the first farmer_public_key (fingerprint 2224278739)in my key list by default. In fact I use the third key (fingerprint 3210875025)as a farmer joining the pool and it works. Why?

![image](https://user-images.githubusercontent.com/15166591/123406952-064b8280-d5de-11eb-8006-21bdd207d4db.png)

**Comment by mariano54** [comment]
the farmer public key and be any one of the keys that are in the keychain of your farmer machine.
