### ISSUE TITLE
Farmer coin is missing

### ISSUE THREAD

**Issue by neal-zhu** [Chia-Network/pool-reference#110]
Hey I tested pool with a single farmer, and my farmer had mined two blocks but both of them did not claim farmer coin(0.25 txch). But pool claimed pool coin and distributed it to farmer

**Comment by mariano54** [comment]
Did you check the target rewards address in the config file? The 0.25XCH reward works exactly the same as before.

**Comment by neal-zhu** [comment]
I used gui and did not change anything in config.yaml. And I can get rewards from pool, so I think config file is fine

**Comment by mariano54** [comment]
do you have multiple keys?

**Comment by neal-zhu** [comment]
Yes, I have two keys

**Comment by mariano54** [comment]
it might be in the other key then. 0.25XCH is paid out to farmer.xch_target_address in the config

**Comment by mariano54** [comment]
Closing since this is not an issue

**Comment by neal-zhu** [comment]
@mariano54 No  it is an issue, 0.25 xch is not found in any of my keys.
