### ISSUE TITLE
can send me one TXCH in testnet9? i want to test pools, please

### ISSUE THREAD

**Issue by lpf763827726** [Chia-Network/pool-reference#112]
I checkout `testnet9` branch, i found my TXCH is 0, i can't join my pool test

My disk only can plot the k25, and Estimated network space is 8.6T now, it need too long time to win

Can you send me one TXCH, please, i want to join my pool and keep test

my wallet is: txch1cc2cu0ngvej0j8dlu6gz7ataq07e884802cnu9yes7cqrfvu0mvq0kj2ju

**Comment by yhhwpp** [comment]
https://faucet.chia.net/ or https://chia2start.eu/

**Comment by lpf763827726** [comment]
> https://faucet.chia.net/ or https://chia2start.eu/

thanks for the answer :)
