### ISSUE TITLE
Do you build NFT plot in testnet  or mainnet?

### ISSUE THREAD

**Issue by a-bahmani** [Chia-Network/pool-reference#114]
Hi there,
I tried to build nft plot in testnet but I got "not enough balance", I went to Chia Faucet site but I got "invalid address"! 
Should I create my nft plot with mainnet or testnet?
Thanks

**Comment by mariano54** [comment]
chia faucet is for mainnet.
You can create it in either testnet or mainnet, but you need to have some chia available first.
