### ISSUE TITLE
We need mining pool stratum

### ISSUE THREAD

**Issue by z1617** [Chia-Network/pool-reference#12]
Current implementation isn't good.

Please refer other PoW mining stratum, there are some suggestions:

1. Use JSON RPC, (including `mining.authorize`, `mining.subscribe`, `mining.notify`, `mining.submit` methods), [BitCoin Stratum mining protocol](https://en.bitcoin.it/wiki/Stratum_mining_protocol).
2. Make pool harvester stateless, like hpool's harvester client, only communicate with pool server.
3. Use PPLNS payment method, we need a block unlocker to distribute block rewards among mining accounts base on their submitted shares(points), and payment system schedule those pending payouts.

If the reference pool supports such features, other pools can adapt those to their system easily which will make chia more decentralized.

**Comment by z1617** [comment]
If the reference pool supports such features, other pools can adapt those to their system easily which will make chia more decentralized.

**Comment by mariano54** [comment]
1. JSON RPC is used, although the protocol has been simplified from stratum to only include POST /partial. This allows setting difficulty as well as changing payout information. Please check SPECIFICATION.md. Is there any other feature that you are looking for?
2. You can run the harvester + farmer with no database and connect to an external full node. You will have to change the settings of the chia app to point to a different full node.
3. The code already does do this, and you can customize this however you want. Is there some change you would like to make?

**Comment by z1617** [comment]
>     1. JSON RPC is used, although the protocol has been simplified from stratum to only include POST /partial. This allows setting difficulty as well as changing payout information. Please check SPECIFICATION.md. Is there any other feature that you are looking for?
> 
>     2. You can run the harvester + farmer with no database and connect to an external full node. You will have to change the settings of the chia app to point to a different full node.
> 
>     3. The code already does do this, and you can customize this however you want. Is there some change you would like to make?

Thanks for your reply @mariano54, the `SPECIFICATION.md` is very good for developers.
