### ISSUE TITLE
Error creating plot NFT: {'error': 'Not enough balance in main wallet to create a managed plotting pool.', 'success': False}

### ISSUE THREAD

**Issue by herotm** [Chia-Network/pool-reference#122]
Error creating plot NFT: {'error': 'Not enough balance in main wallet to create a managed plotting pool.', 'success': False}

**Comment by herotm** [comment]
i set the pool fee to 0.00, still showing error

**Comment by william-gr** [comment]
You need balance in the client wallet to create a pool nft.

**Comment by yhhwpp** [comment]
https://faucet.chia.net/  get the txch
