### ISSUE TITLE
cant sync testnet since use pools.testnet9 or main branch

### ISSUE THREAD

**Issue by neal-zhu** [Chia-Network/pool-reference#123]
Following your step but can not sync test net. Output of chia show -s
`
Searching for an initial chain

You may be able to expedite with 'chia show -a host:port' using a known node.

Blockchain has no blocks yet`

What have you guys done?
![image](https://user-images.githubusercontent.com/34360891/124160632-07dde480-dacf-11eb-8f11-566385b584c6.png)
Things were fine when using pools.dev with this repo, what's the point of keep changing branch?

I cant event test pools any more

**Comment by wjblanke** [comment]
plots.testnet9 will run testnet9 out of the box. you shouldn't run chia configure--that will switch it to testnet7.

we moved to testnet9 as it uses a new smart contract for plots.

**Comment by neal-zhu** [comment]
So mainnet of pools.testnet9 is actually a testnet?
Why I use branch main and still wont work?

**Comment by neal-zhu** [comment]
Just tell me the right step to setup a test node. Steps in readme not work anymore !

**Comment by neal-zhu** [comment]
Use main branch cant not sync testnet7 or testnet9 !

**Comment by neal-zhu** [comment]
@wjblanke
