### ISSUE TITLE
Singleton for Pool does not sync with second farm

### ISSUE THREAD

**Issue by ASPANSolutions** [Chia-Network/pool-reference#127]
A second farm does not sync the singleton and pool membership to a second farm on Windows GUI.  Is this expected behaviour?

**Comment by wjblanke** [comment]
Are you using the same key on the second farm?

**Comment by ASPANSolutions** [comment]
Yes, the keys are the same. Wallet address, balances etc match.  On first wallet shows block 50948 transaction in outbound (e.g. setting up pool) value 0.000000000001, and on 2nd farm shows as incoming value 0.000000999999
.

**Comment by mariano54** [comment]
you can't see outgoing transactions when syncing up a second wallet.
However, you should be able to see the plotNFT in the pools page. You do not see it?

**Comment by ASPANSolutions** [comment]
No, the pools page is empty and only offers setting up a new pool.

**Comment by mariano54** [comment]
Is your second wallet fully synced up?

**Comment by ASPANSolutions** [comment]
Wallets, were and are, synced up to date before updating the GUI.

**Comment by xiaoxiez** [comment]
我一开始也没有办法同步NFT，那时候使用的是1.1.784版本，再使用1.1.797版本后，在安装后的发现已经同步了，或许可以试试。

**Comment by mariano54** [comment]
Yes, please try the latest version and report back.

**Comment by mariano54** [comment]
Perhaps you had multiple keys on the first computer, and on the second computer you only added one of them?

**Comment by ASPANSolutions** [comment]
I will try latest version.  Only one set of keys on the first computer.

**Comment by ASPANSolutions** [comment]
Installed 1.1.792 and sadly still no pool details.

**Comment by xiaoxiez** [comment]
Try this one
https://download-chia-net.s3-us-west-2.amazonaws.com/builds/ChiaSetup-1.1.797.exe

**Comment by ASPANSolutions** [comment]
installed 1.1.797 and again no pool details.

**Comment by ASPANSolutions** [comment]
Good news.  I installed 1.2.0 and although the pool did not sync, I have setup a second Pool and that has synced back.  I believe therefore it was a fault with the original Windows GUI in not creating the pool properly and so will setup on new Pool setup and close down the old one.  This should mean that the problem should not be replicated by other people, or if they do to have confidence in setting up another pool link to same Pool on the second system and it will sync back.

**Comment by ASPANSolutions** [comment]
My third node sync worked perfectly.  This leaves my 2nd node not working properly and the plots on the new node don't seem to be showing on the pool so I fear something very wrong now with the 2nd node.  I am thinking I need to uninstall the node and do a complete reinstall, unless you think there is another method to resolve the issue.

**Comment by mariano54** [comment]
The problem is you need to be on the latest version before you sync past the singleton on the blockchain. So the solution is to update to 1.2.0, delete the wallet DB, and resync it
