### ISSUE TITLE
No module named 'aiohttp but is installed on system

### ISSUE THREAD

**Issue by xslackx** [Chia-Network/pool-reference#13]
Today i try start the pool server, install all requirements but.
When a try start the server a receive this error. 
`root@4b6de2fd419c:~# CHIA_ROOT="/root/.chia/mainnet" ./bin/python pool-reference-main/pool_server.py 
Traceback (most recent call last):
  File "pool-reference-main/pool_server.py", line 7, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'`

Using pip to install module a receive.

`root@4b6de2fd419c:~# pip install aiohttp
Requirement already satisfied: aiohttp in /usr/local/lib/python3.8/dist-packages (3.7.4.post0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp) (3.0.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp) (21.2.0)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.8/dist-packages (from aiohttp) (3.10.0.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.8/dist-packages (from aiohttp) (5.1.0)
Requirement already satisfied: chardet<5.0,>=2.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp) (4.0.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp) (1.6.3)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.8/dist-packages (from yarl<2.0,>=1.0->aiohttp) (3.1)`

I try again using setup.

**Comment by blockinator** [comment]
@xslackx how did you fix that?
