### ISSUE TITLE
Possibility to analyse client metadata when adding a farmer

### ISSUE THREAD

**Issue by mpnowacki-reef** [Chia-Network/pool-reference#133]
Hey,

We're looking for ways to implement fine user identification at `add_farmer` time. What would really help is passing the original `aiohttp.web.Request` instance from the pool server, through the `Pool` instance to `AbstractPoolStore.add_farmer_record`. Thanks to such a tweak, `PoolStore` implementers would be able to:
* identify bad actors and possibly reject them
* narrow down served IP ranges

This is a minor change in the code, but before I write and submit it I would like to ask if it's a welcome change?

**Comment by xiaoxiez** [comment]
welcome

**Comment by xiaoxiez** [comment]
我想知道这个改动会不会导致第二阶段在主网plotter的图在正式发布后失效。

**Comment by mariano54** [comment]
The store is a DB layer interface, it should not deal with IPs or networking objects. We can however pass in specific values like IP, etc.
