### ISSUE TITLE
Don't worry about TLS?

### ISSUE THREAD

**Issue by sfxworks** [Chia-Network/pool-reference#14]
https://github.com/Chia-Network/pool-reference/blob/76615791f64a9afaad856641ed069f9f955c622f/pool_server.py#L130

There exist common TLS reverse proxies such as Nginx. A suggestion for v1 would be to omit time developing this.

**Comment by mariano54** [comment]
TLS is important and it's a requirement.

**Comment by mariano54** [comment]
This is left for pool operators to implement. There is a note of this on the specification.
