### ISSUE TITLE
how connect to mainnet?

### ISSUE THREAD

**Issue by kkpeng** [Chia-Network/pool-reference#149]
i have connect to testnet9 ,but i don't kown how to connect mainnet

**Comment by mariano54** [comment]
use the main branch in chia-blockchain

**Comment by frstrtr** [comment]
Pool URLs must be HTTPS on mainnet http://x.x.x.x:xx. Aborting. How can I start pool-reference with HTTPS support?

**Comment by ppolewicz** [comment]
you need to cover it with an nginx or AWS ELB or something, see also https://github.com/Chia-Network/pool-reference/pull/170
