### ISSUE TITLE
Pool Server can't start with https:// in mainnet 

### ISSUE THREAD

**Issue by vigorcloud** [Chia-Network/pool-reference#150]

**Comment by jack60612** [comment]
I am running a modified version of the reference code fine 
Could you please elaborate?

**Comment by kingdeng1985** [comment]
> I am running a modified version of the reference code fine
> Could you please elaborate?

How to set TLS, the default is HTTP protocol instead of HTTPS protocol, what method do you use to implement the HTTPS protocol?

**Comment by jack60612** [comment]
> > I am running a modified version of the reference code fine
> > Could you please elaborate?
> 
> How to set TLS, the default is HTTP protocol instead of HTTPS protocol, what method do you use to implement the HTTPS protocol?

nginx reverse proxy with waf

**Comment by jack60612** [comment]
@vigorcloud https://docs.aiohttp.org/en/stable/deployment.html

**Comment by kingdeng1985** [comment]
> > > 我正在运行参考代码的修改版本，
> > > 您能详细说明一下吗？
> > 
> > 
> > 如何设置TLS，默认是HTTP协议而不是HTTPS协议，请问你是用什么方式实现HTTPS协议的？
> 
> 带有waf的nginx反向代理

Is it OK for nginx to configure the aiohttp80 port of the HTTPS reverse proxy? Do you have the configuration reference of nginx reverse proxy?

**Comment by jack60612** [comment]
just look up how to setup nginx reverse proxy with lets encrypt

**Comment by ByronAP** [comment]
I think I have the same/similar issue. Testing on my local machine plotnft to https://127.0.0.1:80 returns

> Exception from 'wallet' Error connecting to pool https://127.0.0.1:80: Cannot connect to host 127.0.0.1:80 ssl:default [[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)]

the pool shows

> ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/byron/pool-reference/venv/lib/python3.8/site-packages/aiohttp-3.7.4-py3.8-linux-x86_64.egg/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"

**Comment by ppolewicz** [comment]
@ByronAP do you really have a https service on port 80? https is usually on 443

**Comment by vigorcloud** [comment]
I got an error when excute "chia plotnft create -s pool -u https://192.168.31.228"  :  Exception from 'wallet' Error connecting to pool https://192.168.31.228: Cannot connect to host 192.168.31.228:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')]

Does it means that I can't use my self-signed SSL certificate ?

**Comment by kingdeng1985** [comment]
> 只需查看如何使用让加密来设置 nginx 反向代理

Does Web UI need to be developed on its own. Are you developing?

**Comment by ByronAP** [comment]
> @ByronAP do you really have a https service on port 80? https is usually on 443

DOH

**Comment by jack60612** [comment]
> > @ByronAP do you really have a https service on port 80? https is usually on 443
> 
> DOH

why?????

**Comment by ByronAP** [comment]
> > > @ByronAP do you really have a https service on port 80? https is usually on 443
> > 
> > 
> > DOH
> 
> why?????
That is a Simpsons reference that means I made a stupid mistake.

**Comment by mariano54** [comment]
This is out of scope for the pool-reference
