### ISSUE TITLE
WARNING  Error while handling message: Traceback (most recent call last)

### ISSUE THREAD

**Issue by wearechiarex** [Chia-Network/pool-reference#154]
Hello,
We are getting like this errors on pool logs:
```
2021-07-10T17:22:14.889 pool pool.pool_server             : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/chiarex/pool-reference/pool/pool_server.py", line 68, in inner
    res_object = await f(request)
  File "/home/chiarex/pool-reference/pool/pool_server.py", line 226, in get_login
    signature: G2Element = G2Element.from_bytes(hexstr_to_bytes(request_obj.rel_url.query["signature"]))
  File "/home/chiarex/pool-reference/venv/lib/python3.8/site-packages/chia/util/byte_types.py", line 11, in hexstr_to_bytes
    return bytes.fromhex(input_str)
ValueError: non-hexadecimal number found in fromhex() arg at position 192
```

**Comment by mariano54** [comment]
Looks like an error in `get_login_link`, are you doing anything different on the client side?

**Comment by wearechiarex** [comment]
Yeap we did this to pool_server.py:
`#Added by Chiarex Team
import ssl`
and:
`    #Added by Chiarex Team
    ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    ssl_context.load_cert_chain('/home/chiarex/ssl-certs/tr.node.chiarex.net-certificate.crt', '/home/chiarex/ssl-certs/tr.node.chiarex.net-private.key')
    #site = aiohttp.web.TCPSite(runner, "0.0.0.0", int(80))
    site = aiohttp.web.TCPSite(runner, "0.0.0.0", int(443), ssl_context=ssl_context)
`

**Comment by jack60612** [comment]
> Yeap we did this to pool_server.py:
> 
> ```
> #Added by Chiarex Team
> import ssl
> ```
> 
> and added:
> 
> ```
>     ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
>     ssl_context.load_cert_chain('/home/chiarex/ssl-certs/tr.node.chiarex.net-certificate.crt', '/home/chiarex/ssl-certs/tr.node.chiarex.net-private.key')
>     #site = aiohttp.web.TCPSite(runner, "0.0.0.0", int(80))
>     site = aiohttp.web.TCPSite(runner, "0.0.0.0", int(443), ssl_context=ssl_context)
> ```

dont use ssl built in Use a nginx reverse proxy and a waf like modsecurity

**Comment by wearechiarex** [comment]
``

> > Yeap we did this to pool_server.py:
> > ```
> > #Added by Chiarex Team
> > import ssl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and added:
> > ```
> >     ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
> >     ssl_context.load_cert_chain('/home/chiarex/ssl-certs/tr.node.chiarex.net-certificate.crt', '/home/chiarex/ssl-certs/tr.node.chiarex.net-private.key')
> >     #site = aiohttp.web.TCPSite(runner, "0.0.0.0", int(80))
> >     site = aiohttp.web.TCPSite(runner, "0.0.0.0", int(443), ssl_context=ssl_context)
> > ```
> 
> dont use ssl built in Use a nginx reverse proxy and a waf like modsecurity

Can we use Cloudflare?

**Comment by jack60612** [comment]
> ``
> 
> > > Yeap we did this to pool_server.py:
> > > ```
> > > #Added by Chiarex Team
> > > import ssl
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and added:
> > > ```
> > >     ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
> > >     ssl_context.load_cert_chain('/home/chiarex/ssl-certs/tr.node.chiarex.net-certificate.crt', '/home/chiarex/ssl-certs/tr.node.chiarex.net-private.key')
> > >     #site = aiohttp.web.TCPSite(runner, "0.0.0.0", int(80))
> > >     site = aiohttp.web.TCPSite(runner, "0.0.0.0", int(443), ssl_context=ssl_context)
> > > ```
> > 
> > 
> > dont use ssl built in Use a nginx reverse proxy and a waf like modsecurity
> 
> Can we use Cloudflare?

yes use nginx with cloudflare as just running the server directly is quite bad

**Comment by wearechiarex** [comment]
Closed issue. Problem => selfcodes...
