### ISSUE TITLE
Start pool no messages?

### ISSUE THREAD

**Issue by MacHatter1** [Chia-Network/pool-reference#160]
When I follow the commands listed I get no messages from the pool that it has started?[
<img width="567" alt="Screenshot 2021-07-12 at 23 17 21" src="https://user-images.githubusercontent.com/87342167/125363110-f1097e80-e367-11eb-93bb-8f6d758ed62a.png">
](url)

**Comment by mariano54** [comment]
Wait a few minutes? Also try adding logging to constructors. It's not a lot of code.
