### ISSUE TITLE
one bug

### ISSUE THREAD

**Issue by rocqina** [Chia-Network/pool-reference#164]
https://github.com/Chia-Network/pool-reference/blob/e9f853711cde62c303dd3094168c210769eef10e/pool/pool.py#L664

farmer_record.suggested_difficulty != request.payload.suggested_difficulty
should be =>
 farmer_record.difficulty != request.payload.suggested_difficulty

**Comment by mariano54** [comment]
You are right, thank you.

**Comment by mariano54** [comment]
https://github.com/Chia-Network/pool-reference/pull/187
