### ISSUE TITLE
No farming after 24 hours after joining the mining pool

### ISSUE THREAD

**Issue by qq597353** [Chia-Network/pool-reference#167]
![chia pool](https://user-images.githubusercontent.com/26955326/125468999-5c03739f-5d0d-48a9-b49c-c646e90b0bc7.jpg)
No farming after 24 hours after joining the mining pool

**Comment by ppolewicz** [comment]
What makes you think it's pool-reference at fault here? You should contact migpool, not post on this github

**Comment by mariano54** [comment]
Please try a different pool.
Also are you plotting with 1.2.0+ plotter or with madmax?
Plotting with old version of plotter will NOT work.

**Comment by mariano54** [comment]
Closing.
