### ISSUE TITLE
get_most_recent_singleton_coin_from_coin_solution 

### ISSUE THREAD

**Issue by neal-zhu** [Chia-Network/pool-reference#171]
ImportError: cannot import name 'get_most_recent_singleton_coin_from_coin_solution' from 'chia.pools.pool_puzzles' (/home/ray/pool-reference/venv/lib/python3.8/site-packages/chia/pools/pool_puzzles.py)

apparently your code doesnot work with chia node, can you do some test before merge codes into main master since this is the code for all devs to reference.
How could we develop if this does not work at all????

**Comment by xdustinface** [comment]
See https://github.com/Chia-Network/pool-reference/pull/168, this repo is just not yet adjusted to the latest changes from yesterday in `chia-blockchain/main`.
