### ISSUE TITLE
 Cannot connect to host 192.168.0.75:80 ssl:default [[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)]

### ISSUE THREAD

**Issue by michalcach** [Chia-Network/pool-reference#175]
After installing the pool-reference I've got issue connecting to it.

When using 80 port I've got an error:
> Exception from 'wallet' Error connecting to pool https://192.168.0.75:80: Cannot connect to host 192.168.0.75:80 ssl:default [[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)]

trying with no port or default 443 gives connection error:
>Exception from 'wallet' Error connecting to pool https://192.168.0.75: Cannot connect to host 192.168.0.75:443 ssl:default [Connect call failed ('192.168.0.75', 443)]

It seems I'm missing setup for secure connection...

**Comment by ppolewicz** [comment]
indeed. mainnet pools need to be `https` - you need to install nginx or something to handle httos for you, you also need to get a certificate and figure out how to renew it.

Please observe that pool-reference is not really intended to be run on production. It's to show how to implement a pool. There are many features of a pool that every production pool will want to have, such as leaderboards, making sure you don't violate the US law by sending rewards to countries which US forbids to interact with, making sure you don't do something silly if someone sends 1 mojo to the pool NFT, implementing some kind of a "user area" where they can see things private to their account, actually showing them something (like their current estimated capacity) or even just being able to tell how much effective capacity does your pool have in total. That's all not in the reference pool. You can either ignore those, implement them yourself or hire someone to do it. Maybe one day someone will create an opensource production-quality pool and you can use that, but so far it doesn't look like it's going to happen.

**Comment by jianghushinian** [comment]
https support for reference https://github.com/Chia-Network/pool-reference/pull/170
