### ISSUE TITLE
How to know a CoinRecord is comes from a absorb transaction?

### ISSUE THREAD

**Issue by baguettex** [Chia-Network/pool-reference#177]

**Comment by mariano54** [comment]
Look at the parent coin_id, then get the coin record from that.
Now we need to check if it's a singleton.
Obtain all extra data (PoolState object, look at singleton.py on how to to that).
Finally, reconstruct the puzzle hash from pool state, and compare with the puzzle hash of the parent .

A simple hack would be to check if the amount ==  1.75XCH.

**Comment by ppolewicz** [comment]
@baguettex are you, by any chance, going to implement this check properly? Feels like a waste to do it twice.
