### ISSUE TITLE
authentication_public_key  

### ISSUE THREAD

**Issue by pref-mail** [Chia-Network/pool-reference#179]
A signature certificate is required in the mine pool agreement 
"authentication_public_key" where we can find this public key

**Comment by jianghushinian** [comment]
get launcher_id: `chia plotnft show`, then: `chia plotnft get_login_link -l {launcher_id}`.

**Comment by pref-mail** [comment]
Thank you so much! I found "authentication_public_key" in the log information of the mine pool, but I ran into a new problem, and I found that the parameters passed in the BLS signature were the private key code here  
"
sk: PrivateKey = AugSchemeMPL.key_gen(seed) 
signature: G2Element = AugSchemeMPL.sign(sk, message)"

I don't know if there's a problem with my understanding

**Comment by jianghushinian** [comment]
On the pool side, authentication_public_key in the farmer table. you can look [here](https://github.com/Chia-Network/pool-reference/blob/main/pool/store/sqlite_store.py#L37).

For BLS signature, please refer to the [chia-blockchain project](https://github.com/Chia-Network/chia-blockchain/blob/main/chia/farmer/farmer.py#L537).
