### ISSUE TITLE
https://pooloficial.fragasoft.com.br/pool_info 404 Not Found

### ISSUE THREAD

**Issue by AirtonFraga** [Chia-Network/pool-reference#184]
https://pooloficial.fragasoft.com.br
Chia reference pool

OK 

https://pooloficial.fragasoft.com.br/pool_info

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

any suggestions for configuring?

**Comment by stotiks** [comment]
Show nginx config

**Comment by AirtonFraga** [comment]
server {
        server_name         pooloficial.fragasoft.com.br;
        client_max_body_size  200M;

#      root /var/www/html;
        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.


            proxy_pass                          http://127.0.0.1:8080;

            proxy_set_header                    Host $host;

            proxy_set_header X-Forwarded-Host   $server_name;

            proxy_set_header X-Real-IP          $remote_addr;

            try_files $uri $uri/ =404;

        }

**Comment by stotiks** [comment]
Remove

try_files $uri $uri/ =404;

**Comment by AirtonFraga** [comment]
thank you very much   friend @stotiks, 

{"authentication_token_timeout": 5, "description": "(example) The Reference Pool allows you to pool with low fees, paying out daily using Chia.", "fee": "0.01", "logo_url": "https://www.chia.net/img/chia_logo.svg", "minimum_difficulty": 10, "name": "The Reference Pool", "protocol_version": 1, "relative_lock_height": 32, "target_puzzle_hash": ""}

that worked

**Comment by mariano54** [comment]
Thank you stotiks.
