### ISSUE TITLE
keys clarification in instruction

### ISSUE THREAD

**Issue by chrishp** [Chia-Network/pool-reference#185]
There are 3 wallets we need to create:  block chain reward, pool fee payout and test user wallets.

In config.yaml  we have:

default_target_address:   First wallet address for blockchain rewards.
pool_fee_address:  First wallet address for pool fee payout.
wallet_fingerprint:  Which wallet?
wallet_id:  Where does this come from?

**Comment by mariano54** [comment]
wallet fingerprint for the default target address
wallet id should almost always be 1.
