### ISSUE TITLE
How points (partial) are calculated for two different computer with same launcher ID (same nft) joining the same pool server?

### ISSUE THREAD

**Issue by michealChin** [Chia-Network/pool-reference#188]
Both farmer are using same private key and same nft but located in two separate computer.
I have a several question here:

1) Regarding to GET /farmer, Is it launcher_id, authentication_token and signature will be identically equal for both farmer?
2) Is it the partial was submitted separately to the server by two different farmer and the server add up one by one of them? For example Farmer one with 100 plots submitted 10 partial and farmer two with 1000 plots submitted 100 partial and the server will add up partials from farmer one and farmer two and store in one record with Id Launcher as primary key?

Thanks in advance!

**Comment by ppolewicz** [comment]
your understanding is correct, it will be 110 partials. In fact the pool server doesn't really care how many computers participate (btw what is a computer anyway? with virtualization, dockers, serverless computing and whatnot it's not easy to say). Even if you tried to tell how many computers a given launcher_id has, if they are hidden behind a NAT and they communicate from the same IP address, it's virtually impossible to tell. Maybe it's the same computer, maybe it's not. Maybe farmer one moved all of its plots to farmer two and now there's just one. Doesn't really matter :)

**Comment by michealChin** [comment]
> your understanding is correct, it will be 110 partials. In fact the pool server doesn't really care how many computers participate (btw what is a computer anyway? with virtualization, dockers, serverless computing and whatnot it's not easy to say). Even if you tried to tell how many computers a given launcher_id has, if they are hidden behind a NAT and they communicate from the same IP address, it's virtually impossible to tell. Maybe it's the same computer, maybe it's not. Maybe farmer one moved all of its plots to farmer two and now there's just one. Doesn't really matter :)

Thanks!
