### ISSUE TITLE
Missing metadata for update_farmer_later

### ISSUE THREAD

**Issue by jack60612** [Chia-Network/pool-reference#192]
Jul 20 03:20:12 ip-10-1-1-83 python[730540]: ERROR:asyncio:Task exception was never retrieved
Jul 20 03:20:12 ip-10-1-1-83 python[730540]: future: <Task finished name='Task-60' coro=<Pool.update_farmer.<locals>.update_farmer_later() done, defined at /mnt/efs/pool-main-code/pool-reference/pool/pool.py:711> exception=TypeError("add_farmer_record() missing 1 required positional argument: 'metadata'")>
Jul 20 03:20:12 ip-10-1-1-83 python[730540]: Traceback (most recent call last):
Jul 20 03:20:12 ip-10-1-1-83 python[730540]:   File "/mnt/efs/pool-main-code/pool-reference/pool/pool.py", line 713, in update_farmer_later
Jul 20 03:20:12 ip-10-1-1-83 python[730540]:     await self.store.add_farmer_record(FarmerRecord.from_json_dict(farmer_dict))
Jul 20 03:20:12 ip-10-1-1-83 python[730540]: TypeError: add_farmer_record() missing 1 required positional argument: 'metadata'

**Comment by mariano54** [comment]
Fixed by https://github.com/Chia-Network/pool-reference/pull/195

**Comment by jack60612** [comment]
@mariano54 
Thank you!
