### ISSUE TITLE
Very rare recalc of difficulty if difficulty set high.

### ISSUE THREAD

**Issue by lemur73** [Chia-Network/pool-reference#193]
Currently difficulty is lowered in 2 cases:
1. There were no partials for 1 hour.
2. When target number of partials reached.

In the scenario when farmer generates one partial, lets say every 30 minutes he will be able to accumulate number_of_partials_target in more than 6 days, so he will get less than 50 partials in 24 hours - much less than target 300 in 24 hours.

**Comment by mariano54** [comment]
Yes this is a pretty good idea
