### ISSUE TITLE
Can I still farming when the pool server is down?

### ISSUE THREAD

**Issue by michealChin** [Chia-Network/pool-reference#198]
> The farmer communicates with one or several pools through an HTTPS protocol, and sets their own local difficulty for each pool. Then, when sending signage points to the harvester, the pool difficulty and sub_slot_iters are used. This means that the farmer can find proofs very often, perhaps every 10 minutes, even for small farmers. These proofs, however, are not sent to the full node to create a block. They are instead only sent to the pool. This means that the other full nodes in the network do not have to see and validate everyone else's proofs, and the network can scale to millions of farmers with no issue, as long as the pool scales properly. Since many farmers are part of the pool, only 1 farmer needs to win a block, for the entire pool to be rewarded proportionally to their space.

According to the read me explanation, once a farmer join a pool server, the proof is not sent to full node but to send to the pool. 

1) The proof will be sent to a pool server and pool server will submit the proof to the full node instead of the farmer? 
2)If 1) is correct, the farmer will never win a block if the pool server is down, am I right?

**Comment by hoffmang9** [comment]
Any proof good enough to win will be sent to node and on out to the network. The proofs sent to the pool are at a significantly lower difficulty and only matter for the pool's estimate of your space. The pool win will be handled by the plot NFT and everything will be fine - so you can farm while the pool is down. If the pool stays down too long, you can claim the pool portion back, too.

**Comment by michealChin** [comment]
> Any proof good enough to win will be sent to node and on out to the network. The proofs sent to the pool are at a significantly lower difficulty and only matter for the pool's estimate of your space. The pool win will be handled by the plot NFT and everything will be fine - so you can farm while the pool is down. If the pool stays down too long, you can claim the pool portion back, too.

Thank you for the clarification! It's much clearer now
