### ISSUE TITLE
get_wallet_balance(self.wallet_id) results in Unknown Error

### ISSUE THREAD

**Issue by jadechip** [Chia-Network/pool-reference#20]
Hey there 👋
I have a wallet and full node running but upon starting the server I get the following:
```
INFO:root:Logging in: {'error': 'Unknown Error', 'success': False}
Traceback (most recent call last):
  File "/code/pool_server.py", line 153, in <module>
    asyncio.run(start_pool_server())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/code/pool_server.py", line 128, in start_pool_server
    await server.start()
  File "/code/pool_server.py", line 31, in start
    await self.pool.start()
  File "/code/pool.py", line 170, in start
    res = await self.wallet_rpc_client.get_wallet_balance(self.wallet_id)
  File "/usr/local/lib/python3.8/dist-packages/chia/rpc/wallet_rpc_client.py", line 92, in get_wallet_balance
    return (await self.fetch("get_wallet_balance", {"wallet_id": wallet_id}))["wallet_balance"]
  File "/usr/local/lib/python3.8/dist-packages/chia/rpc/rpc_client.py", line 45, in fetch
    raise ValueError(res_json)
ValueError: {'error': '', 'success': False}
```
I have verified that I can communicate with the wallet via RPC so I am not sure what is going on here.
Are there any additional steps I am missing? Please advise.

I should note that I am pointing to the pooling branch here as opposed to master (when installing Chia).

Thank you!

**Comment by Loki-spec** [comment]
Thank you

**Comment by jadechip** [comment]
Upon digging a bit further, I see a preceding call, `self.wallet_rpc_client.log_in_and_skip`, make calls to `"host": "https://backup.chia.net"`, is this just a placeholder for our own key management server?

**Comment by jadechip** [comment]
Ok, I think I partly found the answer to my own question: 
> You can now backup your wallet related metadata in an encrypted and signed file to a free service from Chia Network at backup.chia.net. Simply having a backup of your private key will allow you to fully restore the state of your wallet including coloured coins, rate limited wallets, distributed identity wallets and many more.
...from this [change log](https://github.com/Chia-Network/chia-blockchain/blob/main/CHANGELOG.md).
Closing for now.
