### ISSUE TITLE
Which port do I need to open?

### ISSUE THREAD

**Issue by nicezic0** [Chia-Network/pool-reference#203]
I want to test the pool service.
The pool service is running on testnet7.
Which port do I need to open? ( port forwarding, mainnet and testent )

Currently, I opened 58444 port in the machine, which is running testnet7 full node and pool service.

**Comment by nicezic0** [comment]
In addtion, I opened port 80 for http, shoing just "Chia reference pool".

**Comment by mariano54** [comment]
Look at pool_server.py. The port is configurable
