### ISSUE TITLE
May I know how to estimate the size of space that farmer contribute to the pool?

### ISSUE THREAD

**Issue by michealChin** [Chia-Network/pool-reference#204]
The farmer could have mix of plot size from k32 and k33, so I would like to know what is the formula to estimate the total space that a farmer contribute to the pool by the partial he submitted to the pool? Thanks!

**Comment by mssc89** [comment]
https://github.com/Chia-Network/chia-blockchain/wiki/Pooling-FAQ#how-does-one-calculate-a-farmers-netspace

Points per 24h should be equal to plot size and count, no matter if they're k32 or larger. k33 will just provide more points (20-22 vs 10 for k32).

**Comment by michealChin** [comment]
> https://github.com/Chia-Network/chia-blockchain/wiki/Pooling-FAQ#how-does-one-calculate-a-farmers-netspace
> 
> Points per 24h should be equal to plot size and count, no matter if they're k32 or larger. k33 will just provide more points (20-22 vs 10 for k32).

Thanks!

**Comment by michealChin** [comment]
> https://github.com/Chia-Network/chia-blockchain/wiki/Pooling-FAQ#how-does-one-calculate-a-farmers-netspace
> 
> Points per 24h should be equal to plot size and count, no matter if they're k32 or larger. k33 will just provide more points (20-22 vs 10 for k32).

How about in testnet7? My farmer got around 86 of plots (k25) but manage to accumulate 200++ of points within half an hour. Is it testnet7 using a different pointing system?
