### ISSUE TITLE
The points that I should receive in testnet7 seems not accurate?

### ISSUE THREAD

**Issue by michealChin** [Chia-Network/pool-reference#208]
According to the Pooling-FAQ for the net space calculation

In mainnet
For 1 bytes per second I should receive 1.088 * 10^-15 points
For k25 plot size, I should receive 1.088*10^-15 * 651996168.192 = 7.092187500029338e-07 points per second
Point in a day for k25 = 0.061276500000253475

In testnet 7 
Points per day need to multiply with 2^67/DIFFICULTY_CONSTANT_FACTOR
= 2^67/10052721566054

For k25 plot size in one second I should receive 1.088*10^-15 * 651996168.192*(2^67/10052721566054) points
= 10.413578479 points.

Let say I have 87 plots (k25), I expected to receive 87 * 10.41 =870 points in a second?

The method I use to get a points per second is take recent 20 partials, Sum all the difficulty (points) / last timestamp - first timestamp, but the value I get is fluctuate between 2 to 10 only. Can some body point out where I am wrong? Thanks!

**Comment by mariano54** [comment]
Hmm has the difficulty adjusted properly? Sometimes the difficulty adjustment is not accurate if you have plots that are too large (k25 is large for testnet). Try increasing your number of plots to around 500 or so.
