### ISSUE TITLE
It's to easy to cheat as a pool admin...

### ISSUE THREAD

**Issue by Tocard** [Chia-Network/pool-reference#211]
Well, hi guys.

I was a coreteam member of https://frenchfarmers.net/ (that's not an advertisement at all.)

Just read at this [thread](https://chiaforum.com/t/suspicious-pools-what-is-happening/10830/70). 

Well, if you see this [api](https://github.com/Tocard/go_api_bootstrap), we was doing three things to cheat on netstat/ partial / point.

# First, netstat.

As you can see on thoses links [api route for miningpoolstat](https://github.com/Tocard/go_api_bootstrap/blob/23729ed5879f4f0edc10de06d686773d367710c8/server/main.go#L62) then  [handler](https://github.com/Tocard/go_api_bootstrap/blob/23729ed5879f4f0edc10de06d686773d367710c8/handlers/miningstatpool.go#L9) then [enter link description here](https://github.com/Tocard/go_api_bootstrap/blob/23729ed5879f4f0edc10de06d686773d367710c8/data/miningstatpool.go#L46) it's easy to cheat on global netspace cuz it's not handle by the pool-reference himself.

```go
func LoadFileSoloPlot() float64 {
content, err := ioutil.ReadFile("solo_plot.txt")
if err != nil {
log.Fatal(err)
}
// Convert []byte to string and print to screen
text := string(content)
Stringfloat := strings.TrimSuffix(text, "\n")
soloNetspace, _ := strconv.ParseFloat(Stringfloat, 64)
return soloNetspace // simply return a float number from a text file as Tib.
}

// GetMiningStatPool return structure for minig stat pool
func GetMiningStatPool() (*MiningStatPool, error) {
toreturn := MiningStatPool{}
fees, feestype := GetFees()
toreturn.Data.PoolStats.Farmers, _ = GetFarmersCount()
toreturn.Data.PoolStats.CurrentFee = fees
toreturn.Data.PoolStats.CurrentFeeType = feestype
toreturn.Data.PoolStats.PoolSpaceTiB, _ = GetNetSpaceTotal() // give an estimation is like say whatever you want
toreturn.Data.PoolStats.PoolSpaceTiB += LoadFileSoloPlot() // add extra Tib to make it bigger.
toreturn.Data.LastBlocks = []LastBlocks{{Height: 585001, Timestamp: 1626533952}}
toreturn.Status = "OK"
return &toreturn, nil
}
```

the direct result here is that
![fake TIB](https://i.ibb.co/LZ45mdk/Capture.png)
more like 7 fake TIB at the begginning.

# Second & Third, Solo plot = add partial & points.
it's not the end.

It was easy to add some solo plot farmer to make the real netspace grow up quickly. Just change pool reward from the chia gui/console and the farmer will get 0.25 , and send 1.75 to the pool wallet.
To make it count as plot nft we did it like that.

[api route to add solo plot point](r.Post%28%22/update/solo_plot%22,%20handlers.PostPartialSoloplot%29)
[api handler to calculate it](https://github.com/Tocard/go_api_bootstrap/blob/23729ed5879f4f0edc10de06d686773d367710c8/handlers/partial.go#L68)

```go
// PostPartialSoloplot post solo plot on bdd share
func PostPartialSoloplot(r *http.Request) (int, string) {
	res := []data.SolotPlot{}
	db := data.GetConn()
	defer db.Close()
	dec := json.NewDecoder(r.Body) //get json from post method with launcher_id and pointPerHour
	dec.Decode(&res)
	t := time.Now().Unix() - 3600 // this is used to set partial from the last hour
	for _, soloFarmer := range res { //for each farmer from the json
		interval := 3600 / soloFarmer.Point // interval is to put partial nor at the same block but split into one hour equally
		farmer, _ := data.GetFarmer(soloFarmer.LauncherId) // stuck it to the launcher_id
		if farmer != nil {
			fmt.Println(farmer.Points, soloFarmer.Point)
			farmer.Points += soloFarmer.Point //add extra point
			err := data.UpdateFarmerPoint(farmer) //fonction to update the farmer
			if err != nil {
				return http.StatusServiceUnavailable, err.Error()
			}	
			for i := 0; i < soloFarmer.Point; i++ { 
				p := data.NewPArtial(soloFarmer.LauncherId, t+int64(interval), 1) // create the partial
				err := p.AddSoloPartial() // function to add partial to bdd equally split into the last hour
				if err != nil {
					return http.StatusServiceUnavailable, err.Error()
				}
				t += int64(interval)
			}
		}
	}
return http.StatusNoContent, "ok"
}
```
as you can see, that was pretty easy to cheat on point & partial. and that was completly transparent from chia and the pool.

at the beginning the idea was to encourage people to stay on chia, and take their solo plot until they replot. it went to something else, lead by the administrator.

The call was made each 15 minutes, it's pretty easy of you harvest this [endpoint](https://api.frenchfarmers.net/partial/all), to see wich partial is fake and not

The difficulty was messed up with that. so if you see leaderboard, there is no difficulty displayed, like that, nobody can see it.

Just checkout at the pool [reward adress](https://www.chiaexplorer.com/blockchain/address/xch16aq8fpg45pdk9v68nsa5kdvvlsfpayca4skjlw8qqfsm6jhks3rq00g0ym) and this [one](https://xchscan.com/address/xch1tepj75jhrh26sd0qja2gqnt4evsx5vz7l9yx6smm0tyeqhu3lusqw58flz) i don't know who is behind it, but it's related to the pool and solo plotting. You can see the 0,25 farmer reward and the 1,75 who go into the pool, and come back to the farmer.

this reward adress is not related to any launcher_id of the pool... Here you can find [the endpoit for all farmer](https://api.frenchfarmers.net/farmer/all)

# We need tracking & clearty.

with both example above, you can see that it's pretty easy to cheat on chia-pool, mainly because of thoses two points.

 - Some critical security points is only at the sight of admin, and people on the pool cannot see it. We need to improve the ability of a pool member to check that the pool protocol is not ripped.
 - Netspace calcul should be included by chia-pool-protocol, to ensure that a launcher_id cannot cheat on the size.

if it was possible to add solo plot like that, partial & point, it was totally possible to create a fake user with many point & partial. I was not able to be on the server, locked by admin (security was call) so i wasn't able to see what my api was used for...

I have wrote thoses code, it was not to scam the community of FrenchFarmer at all. I'm apologized to all other pool who made it legit, and please keep your way on that road !

i'm no longer into the FrenchFarmer community, i have been banned for telling to peoople what was really happening.

Help this post could help Chia.

**Comment by jack60612** [comment]
This is disappointing but sadly expected. In the end you did live up to what you have done which is important, and I believe that everyone in this community values the honesty that you have portrayed. The only real way that we can prevent against fraudulent pools similar to "frenchfarmers", is if we as a community look for outlandish claims and pools that have grown too quickly or are shady. Thankfully this should be the beginning of the end for fraudsters and cheating pools like  "frenchfarmers".
Stay vigilant,
Jack
Owner of https://plotters.club

**Comment by alvaroslm** [comment]
It is possible to track rewards to the pool address and expose all this fraud, maybe in a new website that doesn't just trust the pools' api blindly. Many pools are doing the same or worse...

**Comment by jack60612** [comment]
> It is possible to track rewards to the pool address and expose all this fraud, maybe in a new website that doesn't just trust the pools' api blindly. Many pools are doing the same or worse...

you can just convert the puzzle hash to a wallet address and track it on any explorer

**Comment by alvaroslm** [comment]
> > It is possible to track rewards to the pool address and expose all this fraud, maybe in a new website that doesn't just trust the pools' api blindly. Many pools are doing the same or worse...
> 
> you can just convert the puzzle hash to a wallet address and track it on any explorer

Block explorers don't track coins too well in order to verify they're rewards coming from an nft, but yeah it can be done. It will take a bit of work and someone willing to do it. Sadly, right now, there isn't much incentive to put work on Chia stuff so I don't think we'll have clean pool stats any time soon :/

**Comment by jack60612** [comment]
> > > It is possible to track rewards to the pool address and expose all this fraud, maybe in a new website that doesn't just trust the pools' api blindly. Many pools are doing the same or worse...
> > 
> > 
> > you can just convert the puzzle hash to a wallet address and track it on any explorer
> 
> Block explorers don't track coins too well in order to verify they're rewards coming from an nft, but yeah it can be done. It will take a bit of work and someone willing to do it. Sadly, right now, there isn't much incentive to put work on Chia stuff so I don't think we'll have clean pool stats any time soon :/

yep just honesty at this point

**Comment by Tocard** [comment]
https://chiaforum.com/t/suspicious-pools-what-is-happening/10830/69

I had to close this issue toO, due to personal harassement for it and identity usurpation.
