### ISSUE TITLE
post_farmer response {'error_code': 14, 'error_message': 'Invalid singleton d51040b8eda77ef7cf6e7175d256af43eaaab5fbe78351f452c7fd8ec3bc8d59'}

### ISSUE THREAD

**Issue by pref-mail** [Chia-Network/pool-reference#213]
I built my own mine pool and used testnet7. On another computer, I used the client with testnet7 to intervene in the mine pool, and the mine pool background output: "post_ farmer response {'error_ code': 14, 'error_ message': 'Invalid singleton d51040b8eda77ef7cf6e7175d256af43eaaab5fbe78351f452c7fd8ec3bc8d59'},

**Comment by mariano54** [comment]
Make sure you are on the latest version of chia-blockchain on both computers

**Comment by pref-mail** [comment]
> Make sure you are on the latest version of chia-blockchain on both computers

When this problem occurred, I did not deal with it. In test 7, the network node rewarded me txch !It's amazing!!
