### ISSUE TITLE
Why does my farmer not submit for a long time in the testnet7?

### ISSUE THREAD

**Issue by daxionga** [Chia-Network/pool-reference#214]
I have 5 K32 plots, but after running for 2 days, there is no partial submission, and the connection to the wallet is also very slow. Is this normal?

**Comment by ppolewicz** [comment]
Is your full node synced? Is your wallet synced? Have you checked the logs?

**Comment by mariano54** [comment]
Make sure you plotted on the latest version, not old version.
Do `chia plotnft show` and confirm that your plots are there

**Comment by daxionga** [comment]
thank you,I set the difficulty to 1, and the farmer has submitted it, but it was set to 10 and there was no submission, the difficulty adjustment range is too small

**Comment by jack60612** [comment]
@daxionga has your issue been solved? if so then close the issue

**Comment by mariano54** [comment]
Closing.if this issue is still affecting you, feel free to reopen.
