### ISSUE TITLE
It's to easy to cheat as a pool admin...

### ISSUE THREAD

**Issue by jorisvial** [Chia-Network/pool-reference#215]
Hi,

If you see this [api](https://github.com/Tocard/go_api_bootstrap), three things are used to cheat on netstat/ partial / point.

#  Netstat

![d2ec84ae2b150f550d1206c1088dd88df5323961](https://user-images.githubusercontent.com/9780671/127445574-754dac32-f64d-48f6-98f2-bdb76a9b81b2.png)

# Solo plot = add partial & points

It was easy to add some solo plot farmer to make the real netspace grow up quickly. Just change pool reward from the chia gui/console and the farmer will get 0.25 , and send 1.75 to the pool wallet.
To make it count as plot nft we did it like that.

[api route to add solo plot point](https://github.com/Chia-Network/pool-reference/issues/r.Post%28%22/update/solo_plot%22,%20handlers.PostPartialSoloplot%29)
[api handler to calculate it](https://github.com/Tocard/go_api_bootstrap/blob/23729ed5879f4f0edc10de06d686773d367710c8/handlers/partial.go#L68)

![945e45f0bf46f42ee03de48db2027272f7ad8a2f](https://user-images.githubusercontent.com/9780671/127445708-816a7663-443c-49af-82f6-817217fef08e.png)

As you can see, that was pretty easy to cheat on point & partial. and that was completely transparent from chia and the pool.

At the beginning the idea was to encourage people to stay on chia, and take their solo plot until they replot. it went to something else, lead by the administrator.

The call was made each 15 minutes, it’s pretty easy of you harvest this [endpoint](https://api.frenchfarmers.net/partial/all), to see which partial is fake and not

The difficulty was messed up with that. so if you see leader board, there is no difficulty displayed, like that, nobody can see it.

Just checkout at the pool [reward adress](https://www.chiaexplorer.com/blockchain/address/xch16aq8fpg45pdk9v68nsa5kdvvlsfpayca4skjlw8qqfsm6jhks3rq00g0ym) and this [one](https://xchscan.com/address/xch1tepj75jhrh26sd0qja2gqnt4evsx5vz7l9yx6smm0tyeqhu3lusqw58flz) i don’t know who is behind it, but it’s related to the pool and solo plotting. You can see the 0,25 farmer reward and the 1,75 who go into the pool, and come back to the farmer.

This reward address is not related to any launcher_id of the pool… Here you can find the [endpoint for all farmer](https://api.frenchfarmers.net/farmer/all)

# We need tracking & clarity.

With both example above, you can see that it’s pretty easy to cheat on chia-pool, mainly because of thoses two points.

- Some critical security points is only at the sight of admin, and people on the pool cannot see it. We need to improve the ability of a pool member to check that the pool protocol is not ripped.
- Netspace calcul should be included by chia-pool-protocol, to ensure that a launcher_id cannot cheat on the size.

if it was possible to add solo plot like that, partial & point, it was totally possible to create a fake user with many point & partial. I was not able to be on the server, locked by admin (security was call) so i wasn’t able to see what my api was used for…

~Hope this post could help Chia.~

**Comment by mariano54** [comment]
> Some critical security points is only at the sight of admin, and people on the pool cannot see it. We need to improve the ability of a pool member to check that the pool protocol is not ripped.

Of course a pool operator can change anything on their website, and they can lie about how much space they have. You should not trust the pool operators to tell you how much space they actually have. 

Statistics websites should NOT use the pool's API, they should check on the blockchain, how many blocks each pool is winning. 

> Netspace calcul should be included by chia-pool-protocol, to ensure that a launcher_id cannot cheat on the size.

This is already done by validating partials. If you farm with a solo plot, you cannot get points, since the solo plot proof of space does not have a valid singleton. This is checked here: https://github.com/Chia-Network/pool-reference/blob/main/pool/pool.py#L793, and it is checked when the FarmerRecord is created.

I am not sure what the issue is then. If you find a security bug then you can send it to me @sorgente711 on keybase.

**Comment by SmoothAlabama** [comment]
> > Some critical security points is only at the sight of admin, and people on the pool cannot see it. We need to improve the ability of a pool member to check that the pool protocol is not ripped.
> 
> Of course a pool operator can change anything on their website, and they can lie about how much space they have. You should not trust the pool operators to tell you how much space they actually have.
> 
> Statistics websites should NOT use the pool's API, they should check on the blockchain, how many blocks each pool is winning.
> 
> > Netspace calcul should be included by chia-pool-protocol, to ensure that a launcher_id cannot cheat on the size.
> 
> This is already done by validating partials. If you farm with a solo plot, you cannot get points, since the solo plot proof of space does not have a valid singleton. This is checked here: https://github.com/Chia-Network/pool-reference/blob/main/pool/pool.py#L793, and it is checked when the FarmerRecord is created.
> 
> I am not sure what the issue is then. If you find a security bug then you can send it to me @sorgente711 on keybase.

I think the major point here is that as pool operator, you can cheat as well. If you follow what the api does, it cleary allow operator to change point of farmer by launcher_id, and insert partial as launcher id too.

if you take thoses two things together, you can create a fake farmer on the pool easily and there is any way to check if it's a real farmer or not.

However, if netspace was included & linked to a launcher_id directly, that's totally impossible to do it.

**Comment by jack60612** [comment]
the admin is the admin lol

**Comment by leexhi** [comment]
@jack60612 

So, you accept that as an pool operator admin, you can create fake farmer, give point to him and harvest chia from other ? That's sad

**Comment by ppolewicz** [comment]
as a pool admin you don't even need to go to all this trouble. Creating farmer, giving it points etc is unnecessary - you can just disable the fair share payment function and transfer all the money to yourself (until people catch you on it and leave your pool). The farmers who win will still keep 1/8th of the rewards though.

**Comment by leexhi** [comment]
> as a pool admin you don't even need to go to all this trouble. Creating farmer, giving it points etc is unnecessary - you can just disable the fair share payment function and transfer all the money to yourself (until people catch you on it and leave your pool). The farmers who win will still keep 1/8th of the rewards though.

I haven't checked the whole chia's code. But if you're true, in which case this feature has been done ? I'm not seeing any interest...

Anyway, it's too easy to cheat as a pool admin...

**Comment by jack60612** [comment]
> > as a pool admin you don't even need to go to all this trouble. Creating farmer, giving it points etc is unnecessary - you can just disable the fair share payment function and transfer all the money to yourself (until people catch you on it and leave your pool). The farmers who win will still keep 1/8th of the rewards though.
> 
> I haven't checked the whole chia's code. But if you're true, in which case this feature has been done ? I'm not seeing any interest...
> 
> Anyway, it's too easy to cheat as a pool admin...

Listen how do you suggest we fix that.
A pool admin is a a admin lol

**Comment by leexhi** [comment]
@jack60612

A pool admin is a pool admin should not be a correct answer...

I do not have any magic answer, but if we admin is able to do whatever he wants, it should be public.

**Comment by ppolewicz** [comment]
@leexhi this is not a ticket for the pool-reference repository, I think. If you want to change the Chia protocol so that it makes it much harder to cheat, you should discuss it in some other place (tip: it's practically impossible in off-chain pools while on-chain pools are impractical as the reason for having pools is to offload ). I'm not sure where the right place for this discussion is, though I suggest that you read the Chia paper which explains the approach to proof of space and time.

It is public knowledge that the pool can steal the rewards, "run away with the prize" is the official wording, I think

**Comment by leexhi** [comment]
@ppolewicz if I'm not wrong, we are on a issues about how it's easy to stole people with chia-pooling-protocol.

As products owner, the chia team have to give their position about it. That's what I'm thinking.

Why I'm posting on this thread, just because I'm surprised of how it's hard to trust a pool today...

If you have a link to share, where it's possible to speak about it I will for sure follow it, and I hope some pool operator could join.

**Comment by jack60612** [comment]
> @ppolewicz if I'm not wrong, we are on a issues about how it's easy to stole people with chia-pooling-protocol.
> 
> As products owner, the chia team have to give their position about it. That's what I'm thinking.
> 
> Why I'm posting on this thread, just because I'm surprised of how it's hard to trust a pool today...
> 
> If you have a link to share, where it's possible to speak about it I will for sure follow it, and I hope some pool operator could join.

im a pool operator 
Its all about trust lol.
no way around that

**Comment by leexhi** [comment]
> > @ppolewicz if I'm not wrong, we are on a issues about how it's easy to stole people with chia-pooling-protocol.
> > As products owner, the chia team have to give their position about it. That's what I'm thinking.
> > Why I'm posting on this thread, just because I'm surprised of how it's hard to trust a pool today...
> > If you have a link to share, where it's possible to speak about it I will for sure follow it, and I hope some pool operator could join.
> 
> im a pool operator
> Its all about trust lol.
> no way around that

Making no sense...
As a pool operator, you should encourage a way to look like 100% transparent and not only making your pool on people trust & faith..

If you prefer to respond , an admin is an admin, it's maybe because you don't want to be transparent ?

Just you answer is freaking out

**Comment by hoffmang9** [comment]
The reason we made it easy to leave a pool is because you have to trust the pool admin/operator. If you want true security, don't pool and that requires trusting no one.

**Comment by ppolewicz** [comment]
@leexhi if what you say is true, then pools who make their operation 100% transparent should get lots and lots of users while pools that are opaque should be loosing users to those transparent pools.
The whole hpool situation regrettably shows that people want pooling much more than they want many other things.

If you want to discuss it further, consider subreddit of Chia, the official forums of Chia or keybase.
