### ISSUE TITLE
[BUG]Inaccurate points update！

### ISSUE THREAD

**Issue by pchacker** [Chia-Network/pool-reference#223]
![5cb3789c1e656f9b06fefd1ce98d65a](https://user-images.githubusercontent.com/10546338/127770713-3b0a94b2-7937-46c6-9911-bc8cc8f1e219.png)
![2c3fb6f06dd6f11b761cb733a3d7b17](https://user-images.githubusercontent.com/10546338/127770716-f8d3bbd4-e552-4913-91cb-b0d3b441c64c.png)

Current Points Balance Error！
There are some special circumstances that can cause inaccurate update of points balance.

**Comment by jack60612** [comment]
@pchacker do you know what would cause those special circumstances?

**Comment by mariano54** [comment]
Any updates? Is this cauesd by https://github.com/Chia-Network/pool-reference/pull/239?

**Comment by cai1111** [comment]
https://github.com/Chia-Network/pool-reference/commit/5eebf043dd4cf10812078eb2318c359f8a516556#diff-10dc24571594464ebd37259ed96a907cc3123c480755cb4d14de3f205661ef67L182 the issue has been fixed   @mariano54 @pchacker
