### ISSUE TITLE
[BUG] Logic flaws ！ERROR:7  The aggregate signature is invalid 

### ISSUE THREAD

**Issue by pchacker** [Chia-Network/pool-reference#228]
![paste](https://user-images.githubusercontent.com/10546338/128449189-b19f62ea-3861-4215-83ca-dd149ec9df88.png)

For example, there are multiple harvesters, but on each of them mining is  using the local full node wallet connection pool.The "authentication_public_key" is different for each full-node wallet. This causes the following error.

**Comment by jack60612** [comment]
> ![paste](https://user-images.githubusercontent.com/10546338/128449189-b19f62ea-3861-4215-83ca-dd149ec9df88.png)
> 
> For example, there are multiple harvesters, but on each of them mining is using the local full node wallet connection pool.The "authentication_public_key" is different for each full-node wallet. This causes the following error.

you shouldn't be doing that in the first place
its a bad idea. not a logic flaw.
