### ISSUE TITLE
Error in pooling: Did not find signage point or EOS

### ISSUE THREAD

**Issue by xan-98** [Chia-Network/pool-reference#230]
chia blockchain 1.2.2

farmer chia.farmer.farmer         : ERROR    Error in pooling: (3, 'Did not find signage point or EOS d45c57c963b3d5f3a681a0f5afb8ba754647908f7204de1f919982ac5e6f31fd, None')

farmer chia.farmer.farmer         : ERROR    Error in pooling: (3, 'Did not find signage point or EOS f455500c6dd8bb2f5cfd4d794c239a84a410224570782c0649654f3f7b913756, None')

farmer chia.farmer.farmer         : ERROR    Error in pooling: (3, 'Did not find signage point or EOS f455500c6dd8bb2f5cfd4d794c239a84a410224570782c0649654f3f7b913756, None')

pool log

pool root :   INFO     post_partial response {'error_code': 3, 'error_message': 'Did not find signage point or EOS d0fd4a6d8eec8992b9698de0a5f38dc19d32ad55a0bd77d4b8e999321c9912dd, None'}, time: 10.02328372001648 launcher_id: 0x707a5fe5545cd47f220c7a80c6f72eb4f9cf3545c32d248990043b8980292d13

pool root :   INFO     post_partial response {'error_code': 3, 'error_message': 'Did not find signage point or EOS d3959996add2d8fbcaa093160deef8d28aa729ef1b20923e4fad822751223b82, None'}, time: 10.018839359283447 launcher_id: 0x707a5fe5545cd47f220c7a80c6f72eb4f9cf3545c32d248990043b8980292d13

pool root :   INFO     post_partial response {'error_code': 3, 'error_message': 'Did not find signage point or EOS d3959996add2d8fbcaa093160deef8d28aa729ef1b20923e4fad822751223b82, None'}, time: 10.03123927116394 launcher_id: 0x707a5fe5545cd47f220c7a80c6f72eb4f9cf3545c32d248990043b8980292d13

**Comment by huntingground** [comment]
I am using 1.2.3. and receiving same error.

<img width="1609" alt="Screenshot 2021-08-08 at 20 36 33" src="https://user-images.githubusercontent.com/86905805/128643784-500cddd2-3910-42ed-ab9e-c326609d88f2.png">

**Comment by jack60612** [comment]
This is an issue with the pool you joined. Try joining another pool

**Comment by ppolewicz** [comment]
specifically it looks like full node of that pool is falling out of sync
