### ISSUE TITLE
[QUESTION] timelord chia.timelord.timelord   : WARNING  Too late to infuse block

### ISSUE THREAD

**Issue by wearechiarex** [Chia-Network/pool-reference#233]
"2021-08-08T16:51:37.759 timelord chia.timelord.timelord   : WARNING  Too late to infuse block"
Is it a problem in node of pool?

**Comment by jack60612** [comment]
It is an issue with the timelord as you should not be running a timelord.
if you can not understand this you should not run a pool,

**Comment by jack60612** [comment]
@xdustinface sorry to bother you again but do you mind closing this?

**Comment by wearechiarex** [comment]
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
Is it enough?

**Comment by jack60612** [comment]
> chia_harvester: started
> chia_farmer: started
> chia_full_node: started
> chia_wallet: started
> Is it enough @jack60612 ?

yes
