### ISSUE TITLE
farmer update failure because of multiple payout instruction

### ISSUE THREAD

**Issue by codev-kuk** [Chia-Network/pool-reference#240]
[Issue specification]
- This issue is regarding #points, #payout address, #payout instruction, #farmer update, #difficulty.
- This is an issue about farmers who have multiple farming machines with different payout addresses for each PC.
- We guess that this issue is due to the latest version update of 1.2.3
- When the farmers update their data on the pool server every 10 minutes, they request the pool server to change their payout addresses because the payout address data on pool server is not matched. (They are asking pool server to update)
- After the pool server updates farmers’ payout address which is one of the farmer’s PCs, on the farmer’s client is not the same as pool server’s payout address.

[Problems] 
- After pool farms a block reward and payout, some user’s points are reset to 0, but a few minutes later with their farmer data update on pool server, pool server has a bug that farmers get points which is the last version just before the payout.
 
![스크린샷 2021-08-18 오후 11 28 31](https://user-images.githubusercontent.com/27219422/129916573-761f53e3-9c12-4cc0-971a-002f2b187c36.png)

- Moreover, some farmers who have multiple payout addresses and farming machines have discounts due to failure of farmer data update.
- Due to this failure of farmer data update, their difficulty is not changed.

**Comment by nghiank** [comment]
This is due to update_farmer_later which will use the previous farmer_record. update_farmer_later is meant to update the payout_instruction, authentication_public_key and difficulty but the point is updated too. Hope that help!

**Comment by codev-kuk** [comment]
@nghiank thankyou :)
