### ISSUE TITLE
How does the pool get the height of the block created by the farmer instead of the height of the packaged coinbase transaction?

### ISSUE THREAD

**Issue by daxionga** [Chia-Network/pool-reference#247]
I use node_rpc_client.get_coin_records_by_puzzle_hashes,and  it return a list of coinRecord ,but I can't get the coinRecords for which height's coinbase tx

**Comment by mariano54** [comment]
https://github.com/Chia-Network/pool-reference/blob/main/pool/singleton.py#L125
