### ISSUE TITLE
Cache full node lookups

### ISSUE THREAD

**Issue by chrishp** [Chia-Network/pool-reference#248]
Any tips implementing this?  Thanks

// TODO(pool): these lookups to the full node are not efficient and can be cached, especially for
// scaling to many users
response = await self.node.rpc_client.get_recent_signage_point_or_eos(None, partial.sp_hash)

**Comment by ppolewicz** [comment]
https://docs.python.org/3/library/functools.html#functools.lru_cache - but it doesn't work with `await`, maybe https://github.com/aio-libs/async-lru

**Comment by chrishp** [comment]
I see, is it saying, we should be caching x number of recent_signage_point_or_eos? 

Thanks for your response.

**Comment by ppolewicz** [comment]
typically the requests should be for the recent block so LRU cache should be ok... unless someone tries to poison your cache with dumb requests to destroy your performance via a cache exhaustion attack ;) But I wouldn't worry about that too much

**Comment by mariano54** [comment]
Exactly, you can probably cache for a few seconds, but don't cache for too long. If you cache for more than like 10 seconds, there is a higher chance of reorg. I suggest caching for only 1-2 seconds.

**Comment by chrishp** [comment]
Thank you, really appreciate it.
