### ISSUE TITLE
Fix point update for mariaDB store

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/pool-reference#251]
Please see how it was fixed for sqlite already. Same fix should be done for mariaDB.

**Comment by jack60612** [comment]
does not need to be fixed for maria as there is already an ON DUPLICATE KEY UPDATE which basically does the same thing while being more efficient

**Comment by jack60612** [comment]
maria was Tested in prod and works fine @mariano54

**Comment by mariano54** [comment]
Thanks for the clarification jack.
