### ISSUE TITLE
Create a test block win

### ISSUE THREAD

**Issue by chrishp** [Chia-Network/pool-reference#252]
Is it possible to create a block win on testnet to test the complete flow faster, instead of waiting for a test farmer to win?

Thanks

**Comment by jack60612** [comment]
> Is it possible to create a block win on testnet to test the complete flow faster, instead of waiting for a test farmer to win?
> 
> Thanks

make your own testnet

**Comment by mariano54** [comment]
If you want to make a testnet, check the wiki of chia-blockchain.
Or make some plots on testnet7 to win.
