### ISSUE TITLE
Verify difficulty is correct with partial submission

### ISSUE THREAD

**Issue by duyk16** [Chia-Network/pool-reference#26]
I have 2 questions here
1. Why we trust **suggested_difficulty** from client and save it to db without any verify?
2. How can I verify and partical and current difficulty are valid (maybe when pool update higher difficulty miner still work on smaller diff)?

https://github.com/Chia-Network/pool-reference/blob/25708b29f09c3a65320731d9211ba413232df12f/pool/pool.py#L513

**Comment by harvestpool** [comment]
Your reference is checking just the processing loop from the queue after validation.  I'm sure that it's checked when submitted here 

https://github.com/Chia-Network/pool-reference/blob/25708b29f09c3a65320731d9211ba413232df12f/pool/pool.py#L725

And the code you reference is after the validation has happened for difficulty, signatures, etc.

**Comment by mariano54** [comment]
suggested difficulty is ignored right now. If you want to allow users to use this, you can only change the difficulty after a time delay (like 5 minutes), otherwise it's not secure.
