### ISSUE TITLE
How to change default_target_address in config.yaml Smoothly.

### ISSUE THREAD

**Issue by night-king** [Chia-Network/pool-reference#260]
Our pool is using old wallet (generated in install progress) and i have lost Mnemonic. So i want to change my pool's default_target_address .
I have changed default_target_address to a new wallet address in config.yaml and restart pool. after a while, i found all farmers can't receive pool reward. 
i read the pool source code and  found the reason: farmer's p2_singleton_pluzze is not equal pool's p2_singleton_pluzze.
Here comes the problem, How can i to change farmer's p2_singleton_pluzze or how to  change default_target_address and not effect existing users?

**Comment by mariano54** [comment]
You cannot change the `default_target_address`. If you lose that key, then you need to create a new address, and all of your users must switch to the new pool address.

**Comment by night-king** [comment]
> You cannot change the `default_target_address`. If you lose that key, then you need to create a new address, and all of your users must switch to the new pool address.
If I don’t want users to know that pool changed, can i write some code to execute **[switch to the new pool address]** for user?
such as run POST/farmer rpc interface.

**Comment by mariano54** [comment]
Not supported with current pool specification and reference. If you to do this, you have to convince all users to switch to a new pool, and a run a new server

**Comment by night-king** [comment]
OK，I know.
If I want to merge the users of 2 Pools together, is there any other solution?

**Comment by FazendaPool** [comment]
if you cannot go for the convincing users solution, the only way would be to support those 2 addresses at the same time, but that would require decoupled services on your code so you could share the same userbase
