### ISSUE TITLE
CHIA GUI is not sending partials to Pool. 

### ISSUE THREAD

**Issue by rakesh2906** [Chia-Network/pool-reference#262]
I Am Using Chia GUI 1.2.11 now, I thought the version update would resolve my GUI not sending partial to pool issue but Still happening. 
In order to fix this, I had to restart my Application, and when I start my application plots are not showing in the list.
Even after restarting It will work 5-6 Hours max, Then I had to follow the same process.
I Tried Deleting the config file, Deleting db folder, and re-installed the App totally But am still having the issue. 
I Am Using Ether Connectin, So I can't say wifi having the issue either.

**And I dint face this issue while ruining other Pool nodes like Hpool or foxy. The issue is only with CHIA GUI.**

**Comment by rakesh2906** [comment]
And I dint face this issue while ruining other Pool nodes like Hpool or foxy. The issue is only with CHIA GUI.

**Comment by mariano54** [comment]
This is not currently useful because we have not been able to replicate. If you find a way to replicate (repeatedly see the same issue) please set log level to DEBUG and sent me the log on keybase (sorgente711). Then maybe I can help with the issue.
