### ISSUE TITLE
difficulty is for per harvesters?

### ISSUE THREAD

**Issue by chrishp** [Chia-Network/pool-reference#264]
/update_farmer receives PutFarmerRequest which has no harvester_id.  So updating difficulty here is not relevant if farmer has multiple harvesters correct?  If so, just ignore suggested_difficulty request?

Only /post_partial has harvester_id.

Thanks

**Comment by chrishp** [comment]
Or single difficulty setting can be used for all harvesters for a farmer is fine?

**Comment by chrishp** [comment]
Confirmed difficulty per harvester.

**Comment by chrishp** [comment]
Looks like /get_farmer request response with the difficulty setting that farmer will respect.  However,  /get_farmer request contains no harvester_id, so we can't change difficulty per harvester.

Any ideas?

**Comment by keliew** [comment]
> Looks like /get_farmer request response with the difficulty setting that farmer will respect. However, /get_farmer request contains no harvester_id, so we can't change difficulty per harvester.
> 
> Any ideas?

Apparently, that's by design. Discussion was in #pools on keybase.

**Comment by mariano54** [comment]
Yes the difficulty is per farmer not per harvester.
