### ISSUE TITLE
KeyError: 'memos' send_transaction_multi v1.3.5

### ISSUE THREAD

**Issue by chrishp** [Chia-Network/pool-reference#274]
After upgrading to chia-blockchain 1.3.5, I'm getting this error:

send_transaction_multi
    return await self.client.send_transaction_multi(self.wallet_id, payment_targets, fee=fee)
  File "/home/ubuntu/pool/venv/lib/python3.8/site-packages/chia/rpc/wallet_rpc_client.py", line 149, in send_transaction_multi
    return TransactionRecord.from_json_dict(response["transaction"])
  File "/home/ubuntu/pool/venv/lib/python3.8/site-packages/chia/util/streamable.py", line 381, in from_json_dict
    return dataclass_from_dict(cls, json_dict)
  File "/home/ubuntu/pool/venv/lib/python3.8/site-packages/chia/util/streamable.py", line 72, in dataclass_from_dict
    return klass(**{f: dataclass_from_dict(fieldtypes[f], d[f]) for f in d})
  File "/home/ubuntu/pool/venv/lib/python3.8/site-packages/chia/util/streamable.py", line 72, in <dictcomp>
    return klass(**{f: dataclass_from_dict(fieldtypes[f], d[f]) for f in d})
KeyError: 'memos'

**Comment by jack60612** [comment]
> After upgrading to chia-blockchain 1.3.5, I'm getting this error:
> 
> send_transaction_multi return await self.client.send_transaction_multi(self.wallet_id, payment_targets, fee=fee) File "/home/ubuntu/pool/venv/lib/python3.8/site-packages/chia/rpc/wallet_rpc_client.py", line 149, in send_transaction_multi return TransactionRecord.from_json_dict(response["transaction"]) File "/home/ubuntu/pool/venv/lib/python3.8/site-packages/chia/util/streamable.py", line 381, in from_json_dict return dataclass_from_dict(cls, json_dict) File "/home/ubuntu/pool/venv/lib/python3.8/site-packages/chia/util/streamable.py", line 72, in dataclass_from_dict return klass(**{f: dataclass_from_dict(fieldtypes[f], d[f]) for f in d}) File "/home/ubuntu/pool/venv/lib/python3.8/site-packages/chia/util/streamable.py", line 72, in return klass(**{f: dataclass_from_dict(fieldtypes[f], d[f]) for f in d}) KeyError: 'memos'

Hey are you still having this issue?

**Comment by chrishp** [comment]
Yes,  I reverted my production pool to version v1.2.

There are other issues submitting partial with v1.3.5 as well.  I'm in the process of setting up staging server on testnet to debug this issue.

**Comment by jack60612** [comment]
> Yes, I reverted my production pool to version v1.2.
> 
> There are other issues submitting partial with v1.3.5 as well. I'm in the process of setting up staging server on testnet to debug this issue.

Ill look into it, thanks

**Comment by chrishp** [comment]
It's my bad, some packages weren't updated to 1.3.5.
