### ISSUE TITLE
Can not start node using branch pools.2021-may-25

### ISSUE THREAD

**Issue by rocqina** [Chia-Network/pool-reference#31]
![image](https://user-images.githubusercontent.com/15166591/120461738-d937f580-c3cc-11eb-92c0-19724da2427b.png)

**Comment by jirawong** [comment]
@rocqina  multiple daemon running , please check free port 55400 on your machine

**Comment by rocqina** [comment]
The same output by using chia start all.
And I checked the port 55400 free.
![image](https://user-images.githubusercontent.com/15166591/120465886-09819300-c3d1-11eb-8098-f3f84e4ed079.png)

**Comment by mariano54** [comment]
Try restarting?

**Comment by rocqina** [comment]
I compile and run the chia in the docker ubuntu:20.04,.
The same error after restart any times.

**Comment by harvestpool** [comment]
Are you running in docker?

`sed -i 's/localhost/127.0.0.1/g' ~/.chia/testnet7/config/config.yaml`

see https://github.com/Chia-Network/chia-blockchain/issues/2265#issuecomment-826015294

**Comment by rocqina** [comment]
@harvestpool great，thx
