### ISSUE TITLE
testnet switching - can not find any peer to connect

### ISSUE THREAD

**Issue by opct** [Chia-Network/pool-reference#32]
Following [Install and run (Testnet)](https://github.com/Chia-Network/pool-reference#install-and-run-testnet) steps

When I issued `chia start farmer`, it keeps logging `Invalid handshake` and the sync never complete
```shell
WARNING  Invalid handshake with peer {'host': '*.*.*.*', 'port': 8444}. Maybe the peer is running old software
```

**Comment by jirawong** [comment]
@opct  try `chia show -a node.ecochia.net:58444`
for connect to testnet fullnode

**Comment by mariano54** [comment]
try testnet-node.chia.net
