### ISSUE TITLE
Wrong message during import chia module

### ISSUE THREAD

**Issue by swanduron** [Chia-Network/pool-reference#35]
Hello devs,

Thanks for your hard work on chia pool. I got message once pool_server.py is executed by python3.

ImportError: cannot import name 'SubmitPartial' from 'chia.protocols.pool_protocol' (/usr/local/lib/python3.8/site-packages/chia/protocols/pool_protocol.py)

I have installed chia packet 1.1.6 from rpm and pip install.

Does anything I missed?

**Comment by swanduron** [comment]
System: Centos8
Env: Python3.8
No Python env is installed

**Comment by jirawong** [comment]
@swanduron use chia-blockchain from branch `pools.2021-may-25` to fix problem.

**Comment by mariano54** [comment]
Fixed
