### ISSUE TITLE
problem after reboot, SSL Verification

### ISSUE THREAD

**Issue by FarmingHard** [Chia-Network/pool-reference#36]
Hello

I followed all steps and installed the chia blockchain `pools.2021-may-25 `and then the pool-reference. 
I got the pool to run and everything looked like it worked well. 
However i rebooted the computer and when i tried to start the pool again i get a SSL verification problem, and i have tried to reinstall on a new virtual machine just to make sure i did not mess anything up and it is the same thing after reboot. 

I have not made any changes to any files exept the steps on how to start.

```
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host localhost:85
55 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verif
y failed: certificate signature failure (_ssl.c:1123)')]
```

Maby someone here have an idea on how i messed up?

**Comment by ChiaMineJP** [comment]
Port 8555 is a default port used by a full_node RPC server.
I guess CA certificates between full_node and farmer(or something like that) does not match.

**Comment by Sheldenshi** [comment]
DId you find a solution for this?

**Comment by FarmingHard** [comment]
I have not found any solution yet. Will do more testing today. 
As ChiaMineJP said there is probably something with the CA certificates that get messed up?

**Comment by FarmingHard** [comment]
I did solve it now. Looks like the i had to copy my CA cert from testnet7 folder to mainnet(that by some reason is the folder for testnet7) and everything worked. Don't know why it behaves like this. But it is running again.
