### ISSUE TITLE
get_recent_signage_point_or_eos endpoint clarification

### ISSUE THREAD

**Issue by debug92** [Chia-Network/pool-reference#37]
Please provide more information about "get_recent_signage_point_or_eos" endpoint references. [https://github.com/Chia-Network/pool-reference/blob/main/pool/pool.py#L471](url)
Thanks.

**Comment by ChiaMineJP** [comment]
Check this API documentation.

https://github.com/Chia-Mine/chia-agent/blob/v1.1.0/src/api/rpc/full_node/README.md#get_recent_signage_point_or_eosagent-params

**Comment by mariano54** [comment]
Checks whether a signage point is real and is recent in the blockchain (and has not been reverted). This is used to check if farmers are responding within 28 seconds.
