### ISSUE TITLE
Error creating plot NFT: {'error': 'Not enough balance in main wallet to create a managed plotting pool.', 'success': False}

### ISSUE THREAD

**Issue by arya09021998** [Chia-Network/pool-reference#39]
i have changed fee 0.01 to 0 but still getting message of insufficient fee.
![InkedScreenshot_4_LI](https://user-images.githubusercontent.com/76100875/120761971-609f7900-c533-11eb-98d6-2ccfe34047d7.jpg)

**Comment by mariano54** [comment]
You need to have at least 1 mojo in your wallet
