### ISSUE TITLE
Chia-Network / chia-blockchain install-timelord.sh

### ISSUE THREAD

**Issue by wearechiarex** [Chia-Network/pool-reference#40]
I want to install timelord for pool-reference. I shared details on: https://github.com/Chia-Network/chia-blockchain/issues/6418 . I tried to start pool reference without timelord. I got this error:
``
(venv) [root@node pool-reference]# sudo CHIA_ROOT="/root/.chia/testnet7" ./venv/bin/python pool/pool_server.py
Traceback (most recent call last):
  File "pool/pool_server.py", line 10, in <module>
    from chia.protocols.pool_protocol import SubmitPartial, PoolInfo
ImportError: cannot import name 'SubmitPartial' from 'chia.protocols.pool_protocol' (/root/pool-reference/venv/lib/python3.7/site-packages/chia/protocols/pool_protocol.py)
(venv) [root@node pool-reference]# sudo CHIA_ROOT="/root/.chia/testnet7" ./venv/bin/python pool/pool_server.py
Traceback (most recent call last):
  File "pool/pool_server.py", line 10, in <module>
    from chia.protocols.pool_protocol import SubmitPartial, PoolInfo
ImportError: cannot import name 'SubmitPartial' from 'chia.protocols.pool_protocol' (/root/pool-reference/venv/lib/python3.7/site-packages/chia/protocols/pool_protocol.py)
(venv) [root@node pool-reference]#

``

**Comment by mariano54** [comment]
Are you using the `pools.2021-may-25` branch in chia-blockchain?
