### ISSUE TITLE
Please add farmer machine id in submit partial request

### ISSUE THREAD

**Issue by z1617** [Chia-Network/pool-reference#42]
~~Something like this `request.headers["X-Chia-Worker-Name"] = "rig1"`, so pool side can track each farmer's machine's points.~~

@dataclass(frozen=True)
@streamable
class SubmitPartial(Streamable):
    payload: PartialPayload
    rewards_and_partial_aggregate_signature: G2Element  # Signature of rewards by singleton key, and partial by plot key
    machine_id: Optional[str]

is better, contains a machine_id in the partial payload can help pool side track each machine's data, it's useful for anonymous pool to show farmer's machines, vardiff target to launcher_id or launcher_id+machine_id depends on each pool's implementation.

**Comment by harvestpool** [comment]
This should not be necessary.  It's counter to the philosophy of permissionless pools.  If a farmer wants to track their progress, they can register on a webpage provided by the pool.  The farmer can register their public key and the pool can proceed to associate submissions to their account.

https://github.com/Chia-Network/pool-reference/blob/830b0d0f4a5a708dea670255f82f0c350feb3a59/pool/pool.py#L659

**Comment by z1617** [comment]
> This should not be necessary. It's counter to the philosophy of permissionless pools. If a farmer wants to track their progress, they can register on a webpage provided by the pool. The farmer can register their public key and the pool can proceed to associate submissions to their account.
> 
> https://github.com/Chia-Network/pool-reference/blob/830b0d0f4a5a708dea670255f82f0c350feb3a59/pool/pool.py#L659

Farmer often has multiple machines, use this request header, pool side can track each machine's statistics(latency, reject rate and etc), it's convenient for farmer to monitor their machines.

**Comment by mariano54** [comment]
harvester_node_id was added, so statistics can be tracked.
