### ISSUE TITLE
pool_escaping_innerpuz.clvm.hex not found ... when starting pool_server.py since the update of branch pools.2021-june-4

### ISSUE THREAD

**Issue by LouisLoudogTrottier** [Chia-Network/pool-reference#44]
Not sure if this is a bug or the fact that i screw up de update.

Should i do a fresh install? of both? revert? (chia-blockchain & pool-reference)
If it is a bug, where can i find the instruction fill a proper bug report?
Thanks in adavance

---

I have followed the update process from https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#ubuntudebian on the chia-blockchain repo and then did the step #7 on the pool refrence side https://github.com/Chia-Network/pool-reference#install-and-run-testnet and when i run ` sudo CHIA_ROOT="/home/user/chia-pools/.chia/testnet7" ./venv/bin/python pool/pool_server.py`  i get :

Traceback (most recent call last):
  File "pool/pool_server.py", line 21, in <module>
    from pool import Pool
  File "/home/user/pool-reference/pool/pool.py", line 30, in <module>
    from singleton import create_absorb_transaction
  File "/home/user/pool-reference/pool/singleton.py", line 20, in <module>
    POOL_ESCAPING_MOD = load_clvm("pool_escaping_innerpuz.clvm")
  File "/home/user/pool-reference/venv/lib/python3.8/site-packages/chia/wallet/puzzles/load_clvm.py", line 37, in load_clvm
    return Program.from_bytes(bytes(load_serialized_clvm(clvm_filename, package_or_requirement=__name__)))
  File "/home/user/pool-reference/venv/lib/python3.8/site-packages/chia/wallet/puzzles/load_clvm.py", line 31, in load_serialized_clvm
    clvm_hex = pkg_resources.resource_string(package_or_requirement, hex_filename).decode("utf8")
  File "/home/lltuserpool-reference/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1156, in resource_string
    return get_provider(package_or_requirement).get_resource_string(
  File "/home/user/pool-reference/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1401, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/home/user/pool-reference/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/pool-reference/venv/lib/python3.8/site-packages/chia/wallet/puzzles/pool_escaping_innerpuz.clvm.hex'

**Comment by Nico-VanHaaster** [comment]
Also experiencing the same issue. Have upgraded to the recent release branch for the chia-blockchain
`
Traceback (most recent call last):
  File "pool/pool_server.py", line 21, in <module>
    from pool import Pool
  File "/pool-reference/pool/pool.py", line 30, in <module>
    from singleton import create_absorb_transaction
  File "/pool-reference/pool/singleton.py", line 20, in <module>
    POOL_ESCAPING_MOD = load_clvm("pool_escaping_innerpuz.clvm")
  File "/pool-reference/venv/lib/python3.8/site-packages/chia/wallet/puzzles/load_clvm.py", line 37, in load_clvm
    return Program.from_bytes(bytes(load_serialized_clvm(clvm_filename, package_or_requirement=__name__)))
  File "/pool-reference/venv/lib/python3.8/site-packages/chia/wallet/puzzles/load_clvm.py", line 31, in load_serialized_clvm
    clvm_hex = pkg_resources.resource_string(package_or_requirement, hex_filename).decode("utf8")
  File "/pool-reference/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1156, in resource_string
    return get_provider(package_or_requirement).get_resource_string(
  File "/pool-reference/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1401, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/pool-reference/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/pool-reference/venv/lib/python3.8/site-packages/chia/wallet/puzzles/pool_escaping_innerpuz.clvm.hex'
`

**Comment by Nico-VanHaaster** [comment]
Found this was removed in the commit:
https://github.com/Chia-Network/chia-blockchain/commit/e2bc9a7119e06bed6e9aa82e1399d62e74532d5b

**Comment by LouisLoudogTrottier** [comment]
> Found this was removed in the commit:
> [Chia-Network/chia-blockchain@e2bc9a7](https://github.com/Chia-Network/chia-blockchain/commit/e2bc9a7119e06bed6e9aa82e1399d62e74532d5b)

Do you think we can just copy the file or should we downgrade to this commit? (if that is doable)

**Comment by Nico-VanHaaster** [comment]
I havent traced back why its actually causing a problem to the other branch. Looks like the PR to the new branch was after the rename so it looks like a regression issue.

What I have done is gone back to that specific commit with this sort of steps. 
```
git clone https://github.com/Chia-Network/chia-blockchain.git -b pools.2021-may-25 --recurse-submodules
cd chia-blockchain
git checkout -b working-commit d72452c5c7c468df24a093d24617cf1e57dedf3e \
```

This is purely a work around and requires a rollback to a specific commit.

**Comment by LouisLoudogTrottier** [comment]
Thank you for your insight and providing the steps to rollback, i am still new to git.

**Comment by Nico-VanHaaster** [comment]
No worries. This will leave your branch to the name `working-commit` so after the fix will have to change the branch back to the correct branch but will see what the update will be.

**Comment by LouisLoudogTrottier** [comment]
Not sure waht to expect butseems to be working fine so far. Waiting for the farmer wallet to sync so i can try to make a singleton

>>>
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/pool-reference/venv/lib/python3.8/site-packages/chia/wallet/puzzles/pool_escaping_innerpuz.clvm.hex'
>>>
```
cd venv/lib/python3.8/site-packages/chia/wallet/puzzles/
wget https://raw.githubusercontent.com/Chia-Network/chia-blockchain/d72452c5c7c468df24a093d24617cf1e57dedf3e/chia/wallet/puzzles/pool_escaping_innerpuz.clvm
cd ~/pool-reference
sudo CHIA_ROOT="/home/user/.chia/testnet7" ./venv/bin/python pool/pool_server.py
```

**Comment by wearechiarex** [comment]
Same Issue. I fixed with:
`git clone https://github.com/Chia-Network/chia-blockchain.git -b pools.2021-may-25 --recurse-submodules
cd chia-blockchain
git checkout -b working-commit d72452c5c7c468df24a093d24617cf1e57dedf3e`

**Comment by LouisLoudogTrottier** [comment]
I am currently creating plots, how do i know if it wokrs on testnet?
chia farm status report 15hours until rewards, i am still making plots ti reduce time
Making -k25 plots, is that enought for testnet?
I've been searching for those answers and have more questions, where can i ask them?

**Comment by LouisLoudogTrottier** [comment]
And lastly, as anyone made a bug report or pull request? if it's relevant
I would do it myself if i knew how. As for me, this close the issue.
Regards everyone,
