### ISSUE TITLE
Small issues i notice a few times now

### ISSUE THREAD

**Issue by LouisLoudogTrottier** [Chia-Network/pool-reference#45]
It doesn't really seems to affect anything but while you are doing a  `chia wallet show` on the farmers side,
`ERROR:root:Unexpected error in get_peak_loop: {'error': '', 'success': False}` is thrown in the pool-server output.
And it seems to recover by itself. 

Is this the right place to report small incident like this? If not please advise.
Regards.

![Screenshot from 2021-06-05 15-11-17](https://user-images.githubusercontent.com/56370085/120902789-51422d80-c610-11eb-85c4-0b64c4b056a7.png)

Using the pools.2021-june-4 branch on ubuntu 20.04, and did the following to resolve my previus issue at https://github.com/Chia-Network/pool-reference/issues/44
>>>
FileNotFoundError: [Errno 2] No such file or directory: '/home/llt/pool-reference/venv/lib/python3.8/site-packages/chia/wallet/puzzles/pool_escaping_innerpuz.clvm.hex'
>>>
```
cd venv/lib/python3.8/site-packages/chia/wallet/puzzles/
wget https://raw.githubusercontent.com/Chia-Network/chia-blockchain/d72452c5c7c468df24a093d24617cf1e57dedf3e/chia/wallet/puzzles/pool_escaping_innerpuz.clvm
cd ~/pool-reference
sudo CHIA_ROOT="/home/llt/.chia/testnet7" ./venv/bin/python pool/pool_server.py

**Comment by Sheldenshi** [comment]
Hey, would you mind sending me your email? I am having some trouble running pool server

**Comment by Sheldenshi** [comment]
Your issue can be solved by changing `POOL_ESCAPING_MOD = load_clvm("pool_escaping_innerpuz.clvm")` to `POOL_ESCAPING_MOD = load_clvm("pool_waitingroom_innerpuz.clvm")`

**Comment by canhmai** [comment]
@LouisLoudogTrottier 
![image](https://user-images.githubusercontent.com/58513185/120923838-d43fb280-c6fa-11eb-944b-45de27a3c841.png)

i have done it for you !
