### ISSUE TITLE
What should i do next ? 

### ISSUE THREAD

**Issue by canhmai** [Chia-Network/pool-reference#46]
![image](https://user-images.githubusercontent.com/58513185/120923713-28966280-c6fa-11eb-9c45-6774972cc214.png)
how to connect ? 
dose my pool lauched mainnet or not ? i saw debug log 39xxxx blocks

**Comment by hackmypi** [comment]
Pools are not live on mainnet yet

**Comment by LouisLoudogTrottier** [comment]
If you are at the same point as me, i think the only thing left to do is wait an update
https://github.com/Chia-Network/chia-blockchain/discussions/6491

**Comment by mariano54** [comment]
This should work now.
