### ISSUE TITLE
how can i claim rewards, please help

### ISSUE THREAD

**Issue by arya09021998** [Chia-Network/pool-reference#47]

**Comment by LouisLoudogTrottier** [comment]
From https://github.com/Chia-Network/pool-reference#install-and-run-testnet (last parapgraph)
`**Note that claiming rewards and switching pools are still not enabled**` so i think we need to wait for an update

**Comment by mariano54** [comment]
This has now been enabled. Rewards will be claimed and paid out automatically, assuming your wallet is synced.
