### ISSUE TITLE
How to get mojo in testnet?

### ISSUE THREAD

**Issue by neal-zhu** [Chia-Network/pool-reference#49]
https://faucet.chia.net/ returns Appears invalid address for my testnet addresses. How can I get mojo in testnet to test pool protocol?

**Comment by tmoore22** [comment]
are you using a "txch###" address? with a t?

**Comment by X-Vlad** [comment]
> https://faucet.chia.net/ returns Appears invalid address for my testnet addresses. How can I get mojo in testnet to test pool protocol?

http://chia-faucet.com/

**Comment by neal-zhu** [comment]
@tmoore22 yes and still invalid, but http://chia-faucet.com/ works fine

**Comment by neal-zhu** [comment]
And I also cant sync my wallet for testnet7 with branch pools.2021-june-4, the wallet doest not start syncing

**Comment by MIGPOOL** [comment]
> And I also cant sync my wallet for testnet7 with branch pools.2021-june-4, the wallet doest not start syncing. According to connected peers, it seems my testnode can not connect with any peers

chia show -a testnet-node.chia.net:58444

full node testnet: testnet-node.chia.net port 58444

**Comment by neal-zhu** [comment]
Another problem: 
FileNotFoundError: [Errno 2] No such file or directory: '/Users/zhumaohua/SourceCode/chia-blockchain/chia/wallet/puzzles/pool_escaping_innerpuz.clvm.hex'
It seems there is still missing some puzzle in chia-blockchian

**Comment by mariano54** [comment]
These problems are now fixed.
