### ISSUE TITLE
How to test

### ISSUE THREAD

**Issue by navid-kalaei** [Chia-Network/pool-reference#5]
1. how do maintainers test the functions? is there any reference or unit test available?
1. with regard of issue #1 some SubmitPartial and PoolInfo are not available. do you run based on a custom branch of chia-blockchain?

**Comment by mariano54** [comment]
1. This has not been released yet so we're not providing customer support. There will be instructions as soon as it's runnable on testnet.
2. These are in chia-blockchain. This has not been released yet so we're not providing customer support.
