### ISSUE TITLE
Error creating plot NFT: 'transaction'

### ISSUE THREAD

**Issue by FarmingHard** [Chia-Network/pool-reference#51]
I recive the error message every time i try to create a plotnft when connecting to the pool
Have tried localy on the pool and on a remote farmer. 

`Error creating plot NFT: 'transaction'`

The pool guide says to use this command  `chia poolnft create -u 127.0.0.1:80` But it is not recognised at all. Is it not implemented? 
plotnft works but then i get the first error message `'transaction'.`

**Comment by setar** [comment]
you have 100 mojo on this wallet ?

**Comment by FarmingHard** [comment]
Yes i have several xtch on all wallets testing.

**Comment by setar** [comment]
try
```chia plotnft create -u 127.0.0.1:80```

**Comment by FarmingHard** [comment]
I got it to work with `chia plotnft create -u 127.0.0.1:80` now with the farmer key on the pool server. 
But it wont work on my remote client.

**Comment by FarmingHard** [comment]
I tried with the latest code changes and i can now use my https://subdomain.domain.org to create a plotnft from both local and remote farmers.
