### ISSUE TITLE
ERROR: Can't select amount higher than our spendable balance (double spend when >1 Claimable amount)

### ISSUE THREAD

**Issue by tmoore22** [Chia-Network/pool-reference#63]
Pool payout creates double spend when >1 Claimable amount is collected.. see log below

1. first payout accounts for both 
2. payout tries to send the same payouts again

```
INFO:root:Scanning for block rewards from 1000 to 178298. Found: 2
INFO:root:Claimable amount: 3.5
INFO:root:Not claimable amount: 0.0
INFO:root:Not buried amounts: 0.0
INFO:root:Submitted transaction successfully: 096ca00bc761d4351c7404f9e443a415731387fe7550fd45f8173f27cad718a7

INFO:root:Starting to create payment
INFO:root:Total amount claimed: 3.5
INFO:root:Pool coin amount (includes blockchain fee) 0.035
INFO:root:Total amount to distribute: 3.465
INFO:root:Paying out 355 mojo / point
INFO:root:Will make payments: [{'puzzle_hash': <bytes32: 0c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905>, 'amount': 35000000000}, {'puzzle_hash': <bytes32: c50cd93bf87bc50604a8c6ba4ffc7c74f8ad123e8ae92d2f928417d769c2b17c>, 'amount': 3005670955185}, {'puzzle_hash': <bytes32: 4e5c713d2dc9daad94af550aeb6cd56c471d62f05801ee5f719f76a1a86441a2>, 'amount': 453497893880}, {'puzzle_hash': <bytes32: 537de8b8a1a78e1512862c800db1ad367a1a63f2f991946174222a2a6ddd76c0>, 'amount': 10203765}]
INFO:root:Submitting a payment: [{'puzzle_hash': <bytes32: 0c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905>, 'amount': 35000000000}, {'puzzle_hash': <bytes32: c50cd93bf87bc50604a8c6ba4ffc7c74f8ad123e8ae92d2f928417d769c2b17c>, 'amount': 3005670955185}, {'puzzle_hash': <bytes32: 4e5c713d2dc9daad94af550aeb6cd56c471d62f05801ee5f719f76a1a86441a2>, 'amount': 453497893880}, {'puzzle_hash': <bytes32: 537de8b8a1a78e1512862c800db1ad367a1a63f2f991946174222a2a6ddd76c0>, 'amount': 10203765}]
INFO:root:Transaction: {'additions': [{'amount': 3005670955185,
                'parent_coin_info': '0x849c2cd8fd0b444d9eae5c652c26bd0206414a5217fb1257410ce712539ced86',
                'puzzle_hash': '0xc50cd93bf87bc50604a8c6ba4ffc7c74f8ad123e8ae92d2f928417d769c2b17c'},
               {'amount': 453497893880,
                'parent_coin_info': '0x849c2cd8fd0b444d9eae5c652c26bd0206414a5217fb1257410ce712539ced86',
                'puzzle_hash': '0x4e5c713d2dc9daad94af550aeb6cd56c471d62f05801ee5f719f76a1a86441a2'},
               {'amount': 10203765,
                'parent_coin_info': '0x849c2cd8fd0b444d9eae5c652c26bd0206414a5217fb1257410ce712539ced86',
                'puzzle_hash': '0x537de8b8a1a78e1512862c800db1ad367a1a63f2f991946174222a2a6ddd76c0'},
               {'amount': 35000000000,
                'parent_coin_info': '0x849c2cd8fd0b444d9eae5c652c26bd0206414a5217fb1257410ce712539ced86',
                'puzzle_hash': '0x0c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905'},
               {'amount': 5820947170,
                'parent_coin_info': '0x849c2cd8fd0b444d9eae5c652c26bd0206414a5217fb1257410ce712539ced86',
                'puzzle_hash': '0x41533475e97f5a526cf85185226b008fb73fe8e4e005302f9ab6c317eef22ab5'}],
 'amount': 3494179052830,
 'confirmed': False,
 'confirmed_at_height': 0,
 'created_at_time': 1623340190,
 'fee_amount': 0,
 'name': '0x7f4df74785255d88278313647403b842f503cf27fa8a883b1ae186a0b7ee1cc0',
 'removals': [{'amount': 1750000000000,
               'parent_coin_info': '0xe0238891f563c0b04190f98aa3ca462304e9f1066d4be01c417d07a7994e8197',
               'puzzle_hash': '0x38737d10729bb92f459a2000545eb849d1694ae83e357e801f5cfbed6fd24a90'},
              {'amount': 1750000000000,
               'parent_coin_info': '0xf30448c44f979fbb5659288b7bb7ae04f7778e924be9efa063b38ff497594879',
               'puzzle_hash': '0x38737d10729bb92f459a2000545eb849d1694ae83e357e801f5cfbed6fd24a90'}],
 'sent': 0,
 'sent_to': [],
 'spend_bundle': {'aggregated_signature': '0xb2f60be5deb01f29f93ccf10bd746aaca2bc2918463dc76def4f6cb16ab788c5584bbc40d99d2d7bb6a78e6a7d35dfc6154864aa4194326eccbf0227c5d824b71e36e9f90fdc2d4b17e52541b4eec194e65d40d767e1b983b711cec9d17bdd93',
                  'coin_solutions': [{'coin': {'amount': 1750000000000,
                                               'parent_coin_info': '0xe0238891f563c0b04190f98aa3ca462304e9f1066d4be01c417d07a7994e8197',
                                               'puzzle_hash': '0x38737d10729bb92f459a2000545eb849d1694ae83e357e801f5cfbed6fd24a90'},
                                      'puzzle_reveal': '0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b08138d9333b98960600df8faf6120bc56fdd85799c907732a18f85dfdf706f2a805afbc1d46756a9b3b926a814a6efa15ff018080',
                                      'solution': '0xff80ffff01ffff33ffa0c50cd93bf87bc50604a8c6ba4ffc7c74f8ad123e8ae92d2f928417d769c2b17cff8602bbcff318b180ffff33ffa04e5c713d2dc9daad94af550aeb6cd56c471d62f05801ee5f719f76a1a86441a2ff85699694b3f880ffff33ffa0537de8b8a1a78e1512862c800db1ad367a1a63f2f991946174222a2a6ddd76c0ff84009bb27580ffff33ffa00c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905ff850826299e0080ffff33ffa041533475e97f5a526cf85185226b008fb73fe8e4e005302f9ab6c317eef22ab5ff85015af49ae280ffff3cffa059f2e6f75b3debcee364d0ec952b7254a562c9921c38cd4406d570d32a7bcb418080ff8080'},
                                     {'coin': {'amount': 1750000000000,
                                               'parent_coin_info': '0xf30448c44f979fbb5659288b7bb7ae04f7778e924be9efa063b38ff497594879',
                                               'puzzle_hash': '0x38737d10729bb92f459a2000545eb849d1694ae83e357e801f5cfbed6fd24a90'},
                                      'puzzle_reveal': '0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b08138d9333b98960600df8faf6120bc56fdd85799c907732a18f85dfdf706f2a805afbc1d46756a9b3b926a814a6efa15ff018080',
                                      'solution': '0xff80ffff01ffff3dffa069ece43c9c7f4f9c97a3cc5674b2d1fd5eaf51b2cafff0dd5084e2bc2def9bd28080ff8080'}]},
 'to_puzzle_hash': '0x0c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905',
 'trade_id': None,
 'type': 1,
 'wallet_id': 1}
INFO:root:Total amount claimed: 3.5
INFO:root:Pool coin amount (includes blockchain fee) 0.035
INFO:root:Total amount to distribute: 3.465
INFO:root:Paying out 1102 mojo / point
INFO:root:Will make payments: [{'puzzle_hash': <bytes32: 0c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905>, 'amount': 35000000000}, {'puzzle_hash': <bytes32: 537de8b8a1a78e1512862c800db1ad367a1a63f2f991946174222a2a6ddd76c0>, 'amount': 2436522}, {'puzzle_hash': <bytes32: 4e5c713d2dc9daad94af550aeb6cd56c471d62f05801ee5f719f76a1a86441a2>, 'amount': 351939914828}, {'puzzle_hash': <bytes32: c50cd93bf87bc50604a8c6ba4ffc7c74f8ad123e8ae92d2f928417d769c2b17c>, 'amount': 3110093326398}]
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Not confirmed. In mempool? True
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Not confirmed. In mempool? True
WARNING:root:Pending payments (1), waiting
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Not confirmed. In mempool? True
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: -1
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 0
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 2
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 2
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 2
WARNING:root:Pending payments (1), waiting
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 2
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 2
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 2
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 3
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 3
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 3
WARNING:root:Pending payments (1), waiting
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 4
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 4
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 4
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 4
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 4
WARNING:root:Pending payments (1), waiting
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 7
INFO:root:Farmer 8e86495a1a2b33f1875d554dc59960f5f71cd537f1f00530e35d2b69ae0039588593c0cc677b651f484d752f0fb5e109 updated points to: 958094142
INFO:root:Successfully confirmed payments [{'puzzle_hash': <bytes32: 0c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905>, 'amount': 35000000000}, {'puzzle_hash': <bytes32: c50cd93bf87bc50604a8c6ba4ffc7c74f8ad123e8ae92d2f928417d769c2b17c>, 'amount': 3005670955185}, {'puzzle_hash': <bytes32: 4e5c713d2dc9daad94af550aeb6cd56c471d62f05801ee5f719f76a1a86441a2>, 'amount': 453497893880}, {'puzzle_hash': <bytes32: 537de8b8a1a78e1512862c800db1ad367a1a63f2f991946174222a2a6ddd76c0>, 'amount': 10203765}]
INFO:root:Submitting a payment: [{'puzzle_hash': <bytes32: 0c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905>, 'amount': 35000000000}, {'puzzle_hash': <bytes32: 537de8b8a1a78e1512862c800db1ad367a1a63f2f991946174222a2a6ddd76c0>, 'amount': 2436522}, {'puzzle_hash': <bytes32: 4e5c713d2dc9daad94af550aeb6cd56c471d62f05801ee5f719f76a1a86441a2>, 'amount': 351939914828}, {'puzzle_hash': <bytes32: c50cd93bf87bc50604a8c6ba4ffc7c74f8ad123e8ae92d2f928417d769c2b17c>, 'amount': 3110093326398}]
ERROR:root:Error making payment: {'error': "Can't select amount higher than our spendable balance.  Amount: 3497035677748, spendable:  682189676671", 'success': False}
INFO:root:Submitting a payment: [{'puzzle_hash': <bytes32: 0c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905>, 'amount': 35000000000}, {'puzzle_hash': <bytes32: 537de8b8a1a78e1512862c800db1ad367a1a63f2f991946174222a2a6ddd76c0>, 'amount': 2436522}, {'puzzle_hash': <bytes32: 4e5c713d2dc9daad94af550aeb6cd56c471d62f05801ee5f719f76a1a86441a2>, 'amount': 351939914828}, {'puzzle_hash': <bytes32: c50cd93bf87bc50604a8c6ba4ffc7c74f8ad123e8ae92d2f928417d769c2b17c>, 'amount': 3110093326398}]
ERROR:root:Error making payment: {'error': "Can't select amount higher than our spendable balance.  Amount: 3497035677748, spendable:  682189676671", 'success': False}
```

**Comment by tmoore22** [comment]
disagree, this error continues after all other payment loops have completed... wallet does not have the funds anymore!

**Comment by mariano54** [comment]
I think it's because it's only getting the coins which are buried `confirmation_security_threshold` blocks deep, so it's not seeing the latest payment. Removing this check, and increasing the timeout, should fix this.

**Comment by mariano54** [comment]
Can you try again with the latest push?

**Comment by tmoore22** [comment]
yes, will pull changes and try to re-create.. expect it will take some time to reply with results...

**Comment by tmoore22** [comment]
Looks a lot cleaner, without the second spend attempt!

INFO:root:Starting to create payment
INFO:root:Total amount claimed: 5.25
INFO:root:Pool coin amount (includes blockchain fee) 0.0525
INFO:root:Total amount to distribute: 5.1975
INFO:root:Paying out 92 mojo / point
INFO:root:Will make payments: [{'puzzle_hash': <bytes32: 0c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905>, 'amount': 52500000000}, {'puzzle_hash': <bytes32: 537de8b8a1a78e1512862c800db1ad367a1a63f2f991946174222a2a6ddd76c0>, 'amount': 384000384332}, {'puzzle_hash': <bytes32: c50cd93bf87bc50604a8c6ba4ffc7c74f8ad123e8ae92d2f928417d769c2b17c>, 'amount': 1924835041288}, {'puzzle_hash': <bytes32: 4e5c713d2dc9daad94af550aeb6cd56c471d62f05801ee5f719f76a1a86441a2>, 'amount': 2864357509920}]
INFO:root:Submitting a payment: [{'puzzle_hash': <bytes32: 0c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905>, 'amount': 52500000000}, {'puzzle_hash': <bytes32: 537de8b8a1a78e1512862c800db1ad367a1a63f2f991946174222a2a6ddd76c0>, 'amount': 384000384332}, {'puzzle_hash': <bytes32: c50cd93bf87bc50604a8c6ba4ffc7c74f8ad123e8ae92d2f928417d769c2b17c>, 'amount': 1924835041288}, {'puzzle_hash': <bytes32: 4e5c713d2dc9daad94af550aeb6cd56c471d62f05801ee5f719f76a1a86441a2>, 'amount': 2864357509920}]
INFO:root:Transaction: {'additions': [{'amount': 384000384332,
                'parent_coin_info': '0xdcc08fc57b569f45f53be3513f60ce18abe07eff7f81f75ef899efb8f7533735',
                'puzzle_hash': '0x537de8b8a1a78e1512862c800db1ad367a1a63f2f991946174222a2a6ddd76c0'},
               {'amount': 1924835041288,
                'parent_coin_info': '0xdcc08fc57b569f45f53be3513f60ce18abe07eff7f81f75ef899efb8f7533735',
                'puzzle_hash': '0xc50cd93bf87bc50604a8c6ba4ffc7c74f8ad123e8ae92d2f928417d769c2b17c'},
               {'amount': 2864357509920,
                'parent_coin_info': '0xdcc08fc57b569f45f53be3513f60ce18abe07eff7f81f75ef899efb8f7533735',
                'puzzle_hash': '0x4e5c713d2dc9daad94af550aeb6cd56c471d62f05801ee5f719f76a1a86441a2'},
               {'amount': 52500000000,
                'parent_coin_info': '0xdcc08fc57b569f45f53be3513f60ce18abe07eff7f81f75ef899efb8f7533735',
                'puzzle_hash': '0x0c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905'},
               {'amount': 24307064460,
                'parent_coin_info': '0xdcc08fc57b569f45f53be3513f60ce18abe07eff7f81f75ef899efb8f7533735',
                'puzzle_hash': '0xb4914230485f284d1b58556d175b9908235dad9b0a0322d7d4136e8417a2c9ec'}],
 'amount': 5225692935540,
 'confirmed': False,
 'confirmed_at_height': 0,
 'created_at_time': 1623625909,
 'fee_amount': 0,
 'name': '0x90be9b70495ddcd3e9e1c02ae9ab00374ede2438c9a12691c71690961682016b',
 'removals': [{'amount': 1750000000000,
               'parent_coin_info': '0x835313b216ca4bcbe8362605439ba238e422f22c89588b005409ebea6cfa4663',
               'puzzle_hash': '0x38737d10729bb92f459a2000545eb849d1694ae83e357e801f5cfbed6fd24a90'},
              {'amount': 1750000000000,
               'parent_coin_info': '0x01a2d789ff987a70c9d2afa1b6e06419aa2cc7012e9d9358501da0ffcae3e3a4',
               'puzzle_hash': '0x38737d10729bb92f459a2000545eb849d1694ae83e357e801f5cfbed6fd24a90'},
              {'amount': 1750000000000,
               'parent_coin_info': '0x413e092e03ae765cd535c9b2d32929e05879e2fbc4b80636cc66be84ed156bc1',
               'puzzle_hash': '0x38737d10729bb92f459a2000545eb849d1694ae83e357e801f5cfbed6fd24a90'}],
 'sent': 0,
 'sent_to': [],
 'spend_bundle': {'aggregated_signature': '0x92a3591b8a3d8e0e2a2851556254d09aa10ea235977e3c40c62af74a794b28c4271511f38c5704027a63f8f2adeebc6218f2eb6851d0c93c27e7c7f1ec5f3ac02a8f52cd2316f4f77487919b88683a3e6c183f128888dcdd3439b27035eec941',
                  'coin_solutions': [{'coin': {'amount': 1750000000000,
                                               'parent_coin_info': '0x835313b216ca4bcbe8362605439ba238e422f22c89588b005409ebea6cfa4663',
                                               'puzzle_hash': '0x38737d10729bb92f459a2000545eb849d1694ae83e357e801f5cfbed6fd24a90'},
                                      'puzzle_reveal': '0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b08138d9333b98960600df8faf6120bc56fdd85799c907732a18f85dfdf706f2a805afbc1d46756a9b3b926a814a6efa15ff018080',
                                      'solution': '0xff80ffff01ffff33ffa0537de8b8a1a78e1512862c800db1ad367a1a63f2f991946174222a2a6ddd76c0ff85596834dd4c80ffff33ffa0c50cd93bf87bc50604a8c6ba4ffc7c74f8ad123e8ae92d2f928417d769c2b17cff8601c0291be00880ffff33ffa04e5c713d2dc9daad94af550aeb6cd56c471d62f05801ee5f719f76a1a86441a2ff86029ae9030b2080ffff33ffa00c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905ff850c393e6d0080ffff33ffa0b4914230485f284d1b58556d175b9908235dad9b0a0322d7d4136e8417a2c9ecff8505a8d05e8c80ffff3cffa041a3c0a559e00a318b8875bc760e7ed5fc8cf9fd4baf84d3825e8a76d20617658080ff8080'},
                                     {'coin': {'amount': 1750000000000,
                                               'parent_coin_info': '0x01a2d789ff987a70c9d2afa1b6e06419aa2cc7012e9d9358501da0ffcae3e3a4',
                                               'puzzle_hash': '0x38737d10729bb92f459a2000545eb849d1694ae83e357e801f5cfbed6fd24a90'},
                                      'puzzle_reveal': '0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b08138d9333b98960600df8faf6120bc56fdd85799c907732a18f85dfdf706f2a805afbc1d46756a9b3b926a814a6efa15ff018080',
                                      'solution': '0xff80ffff01ffff3dffa0a919ec70b65ffb85463b0ffb9403c68fdc047e263688f38c6b4be0ab80b489118080ff8080'},
                                     {'coin': {'amount': 1750000000000,
                                               'parent_coin_info': '0x413e092e03ae765cd535c9b2d32929e05879e2fbc4b80636cc66be84ed156bc1',
                                               'puzzle_hash': '0x38737d10729bb92f459a2000545eb849d1694ae83e357e801f5cfbed6fd24a90'},
                                      'puzzle_reveal': '0xff02ffff01ff02ffff01ff02ffff03ff0bffff01ff02ffff03ffff09ff05ffff1dff0bffff1effff0bff0bffff02ff06ffff04ff02ffff04ff17ff8080808080808080ffff01ff02ff17ff2f80ffff01ff088080ff0180ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff17ff80808080ff80808080ffff02ff17ff2f808080ff0180ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff02ff06ffff04ff02ffff04ff09ff80808080ffff02ff06ffff04ff02ffff04ff0dff8080808080ffff01ff0bffff0101ff058080ff0180ff018080ffff04ffff01b08138d9333b98960600df8faf6120bc56fdd85799c907732a18f85dfdf706f2a805afbc1d46756a9b3b926a814a6efa15ff018080',
                                      'solution': '0xff80ffff01ffff3dffa0a919ec70b65ffb85463b0ffb9403c68fdc047e263688f38c6b4be0ab80b489118080ff8080'}]},
 'to_puzzle_hash': '0x0c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905',
 'trade_id': None,
 'type': 1,
 'wallet_id': 1}
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Not confirmed. In mempool? False
INFO:root:Is pool member? True
INFO:root:Farmer af439e8a82b9814d6463dc69f82805225c28c83d78c6e45bb9c72d14ff6239da784edfd4ab22295df0b531041b2d7fd0 updated points to: 4263777642
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Not confirmed. In mempool? True
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Not confirmed. In mempool? True
INFO:root:Is pool member? True
INFO:root:Farmer af439e8a82b9814d6463dc69f82805225c28c83d78c6e45bb9c72d14ff6239da784edfd4ab22295df0b531041b2d7fd0 updated points to: 8527555284
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Not confirmed. In mempool? True
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Not confirmed. In mempool? True
INFO:root:Returning {'points_balance': 0, 'current_difficulty': 4173917221}, time: 0.04331612586975098 singleton: 0xe706cc69221393e93f63a455608570d001b65529c87e398465edebb4710a2cc7
INFO:root:Returning {'points_balance': 0, 'current_difficulty': 4173917221}, time: 0.027251005172729492 singleton: 0xe706cc69221393e93f63a455608570d001b65529c87e398465edebb4710a2cc7
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Not confirmed. In mempool? True
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Not confirmed. In mempool? True
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: -1
INFO:root:Is pool member? True
INFO:root:Farmer ab419bf2911b72a068a755a7fcc43f335afeae9f07b7a0e275a4fb499fbd3e787d882a7f07503de86c2e5b386d952d15 updated points to: 4173917221
INFO:root:Is pool member? True
INFO:root:Farmer ab419bf2911b72a068a755a7fcc43f335afeae9f07b7a0e275a4fb499fbd3e787d882a7f07503de86c2e5b386d952d15 updated points to: 8347834442
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: -1
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 0
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 0
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 0
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 1
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 1
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 1
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 2
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 2
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 2
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 4
INFO:root:Returning {'points_balance': 8527555284, 'current_difficulty': 4263777642}, time: 0.03508949279785156 singleton: 0x96a4b752c331e3259102fd24a03874481de194cf3e98bdb9d0511558e87c829c
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 4
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 4
INFO:root:Waiting for transaction to obtain 6 confirmations
INFO:root:Confirmations: 7
INFO:root:Is pool member? True
INFO:root:Updating singleton state for 96a4b752c331e3259102fd24a03874481de194cf3e98bdb9d0511558e87c829c
INFO:root:Farmer af439e8a82b9814d6463dc69f82805225c28c83d78c6e45bb9c72d14ff6239da784edfd4ab22295df0b531041b2d7fd0 updated points to: 12791332926
INFO:root:Successfully confirmed payments [{'puzzle_hash': <bytes32: 0c9e8b32539ec4559c81dd272a4a29f608cd96641a4acc0f7dd9debecd2b4905>, 'amount': 52500000000}, {'puzzle_hash': <bytes32: 537de8b8a1a78e1512862c800db1ad367a1a63f2f991946174222a2a6ddd76c0>, 'amount': 384000384332}, {'puzzle_hash': <bytes32: c50cd93bf87bc50604a8c6ba4ffc7c74f8ad123e8ae92d2f928417d769c2b17c>, 'amount': 1924835041288}, {'puzzle_hash': <bytes32: 4e5c713d2dc9daad94af550aeb6cd56c471d62f05801ee5f719f76a1a86441a2>, 'amount': 2864357509920}]
`

**Comment by mariano54** [comment]
Great, closing. let me know if you see this error again
