### ISSUE TITLE
 INFO:root:Returning {'error_code': 5, 'error_message': 'Proof of space has required iters 5139170420...

### ISSUE THREAD

**Issue by FarmingHard** [Chia-Network/pool-reference#66]
The pool recives this error message. Is the farmer difficulty to high? Can it be changed some way?

`INFO:root:Returning {'error_code': 5, 'error_message': 'Proof of space has required iters 5139170420, too high for difficulty 643065', 'current_difficulty': 643065}, time: 0.022427797317504883 singleton: 0xd932f4500e8a3da5f893f76d5ecd0bf9a6280ede8182266bcae22b9229437d14`

**Comment by mariano54** [comment]
yes the difficulty is adjusted after receiving this error
