### ISSUE TITLE
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by lpf763827726** [Chia-Network/pool-reference#67]
i follow your "Install and run", use testnet7, chia branch is **pools.2021-may-25**, but why i use **chia version** it will be **1.1.7.dev230**

when i finish setting config,yaml( pool_url, default_target_puzzle_hash, pool_fee_puzzle_hash, wallet_fingerprint ),

i try to run chia start farmer in "chia-blockchain/chia-blockchain-gui", then run sudo CHIA_ROOT="/myhome/.chia/testnet7" ./venv/bin/python pool/pool_server.py in "pool-reference"(they two both in the same dir)

![Screenshot from 2021-06-11 17-41-45](https://user-images.githubusercontent.com/43004977/121667040-7507e680-cadc-11eb-8c00-085014700185.png)
![Screenshot from 2021-06-11 17-43-51](https://user-images.githubusercontent.com/43004977/121667207-9d8fe080-cadc-11eb-8f9d-98d3a1737ce8.png)

why it show me Connection reset by peer?

**Comment by lpf763827726** [comment]
I didn't change files other than config.yaml, please someone help me

**Comment by Powduck-Q** [comment]
> I didn't change files other than config.yaml, please someone help me

1.下载分支git clone https://github.com/Chia-Network/chia-blockchain.git -b pools.2021-may-25 --recurse-submodules

**Comment by lpf763827726** [comment]
> > I didn't change files other than config.yaml, please someone help me
> 
> 1.下载分支并安装
> 
> ```
> git clone https://github.com/Chia-Network/chia-blockchain.git -b pools.2021-may-25 --recurse-submodules
> cd chia-blockchain
> sh install.sh
> . ./activate
> export CHIA_ROOT=".chia/testnet7"
> chia init
> chia configure --testnet true
> chia keys generate 
> chia keys generate
> chia start all 
> ```
> 
> 2.启动一个新的终端,在chia-blockchain 同级目录 下载pool-reference
> 
> ```
> git clone https://github.com/Chia-Network/pool-reference.git
> cd pool-reference
> python3 -m venv ./venv
> source ./venv/bin/activate
> pip install ../chia-blockchain/ 
> ```
> 
> 3.修改config.yaml
> 4.在pool-reference 目录中执行
> 
> ```
> sudo CHIA_ROOT="/root/chia-blockchain/.chia/testnet7/" ./venv/bin/python pool/pool_server.py
> ```

谢谢回答，但是还是不行

在1的`chia start all`的时候报错`FileNotFoundError: can't find vdf_client binary`

然后4的sudo后报错`aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host localhost:8555 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1123)')]`

而且我执行在chia-blockchain里执行`chia stop all`会提示`chia_timelord_launcher: Not running`，其他都正常stop，config.yaml的pool_url我试了`http://127.0.0.1`也是cannot connect

![Screenshot from 2021-06-15 10-01-58](https://user-images.githubusercontent.com/43004977/121981968-39616b00-cdc1-11eb-8c35-808614b55042.png)

**Comment by lpf763827726** [comment]
刚刚和朋友研究了一下，发现好像是我的CHIA_ROOT的问题，现在可以了，非常感谢:)
