### ISSUE TITLE
Question. How can a singleton coin be spent?

### ISSUE THREAD

**Issue by Nico-VanHaaster** [Chia-Network/pool-reference#68]
Looking at the recent code comitts with absorb transaction. I am just curious how can the code below end up with a coin being marked as "spent"

```
 singleton_coin_record: Optional[
                            CoinRecord
                        ] = await self.node_rpc_client.get_coin_record_by_name(rec.singleton_tip.coin.name())
                        if singleton_coin_record is None:
                            continue
                        if singleton_coin_record.spent:
                           self.log.warning(f"Singleton coin {singleton_coin_record.coin.name()} is spent, will not "
                                            f"claim rewards")
                           continue
```

We are just making sure that all the cases are catered for correctly.

**Comment by mariano54** [comment]
When you absorb (claim rewards) or when the user changes their pool, the signelton coin gets spent and a new one is created. When submitting partials, the new one is looked up

**Comment by Nico-VanHaaster** [comment]
@mariano54 Thanks for the details. I am hitting the singleton_coin_record.spent on the only farmer connected to the pool. As far as I am aware we havent changed pools. 

Now when you say 
> When submitting partials, the new one is looked up
Does that mean when ever a new partial is submitted we should update this value in the database?

**Comment by Nico-VanHaaster** [comment]
Sorry, I reread the code and understand how this works. Thanks for the response.
