### ISSUE TITLE
EOS signage points not working with partials

### ISSUE THREAD

**Issue by mariano54** [Chia-Network/pool-reference#70]
Reported by felix

**Comment by mariano54** [comment]
Another report by alex_fp

**Comment by Scorpil** [comment]
I can confirm this is still an issue.

```
2021-06-27T14:38:30.175 full_node chia.full_node.full_node: INFO     ⏲️  Finished sub slot, SP 64/64, fdac0fa110b8d9dae4d410ad67e2b7cf7a66873b573d0ac18a73c7e8a3c3ebea, number of sub-slots: 2, RC hash: 80f16974b6fbb4a7d9d1b1adb70c1d62e7e84ab7b65e1b4ff4906eb581fe59af, Deficit 16
2021-06-27T14:38:42.013 farmer chia.farmer.farmer         : INFO     Pool response: {'error_code': 3, 'error_message': 'Did not find signage point or EOS fdac0fa110b8d9dae4d410ad67e2b7cf7a66873b573d0ac18a73c7e8a3c3ebea, None'}
2021-06-27T14:38:42.013 farmer chia.farmer.farmer         : ERROR    Error in pooling: (3, 'Did not find signage point or EOS fdac0fa110b8d9dae4d410ad67e2b7cf7a66873b573d0ac18a73c7e8a3c3ebea, None')
```

**Comment by mariano54** [comment]
Fixed by:
- https://github.com/Chia-Network/pool-reference/commit/e19586cdd3193b02377a29b00f63aeccd60abef2
- https://github.com/Chia-Network/chia-blockchain/pull/7007

**Comment by JamshaidF** [comment]
I am getting lots of 

post_partial response {'error_code': 3, 'error_message': 'Did not find signage point or EOS c49aad6e973a4cd06913af02dd53dd97952e7de972940265ea5db75031477bee, None'}, time: 10.03007197380066

Only 11 %  success rate.

Percent Successful Points (24h): 11.33%

**Comment by IgorVoiT** [comment]
I can see this in the log sometimes.
` ERROR    Error in pooling: (3, 'Did not find signage point or EOS 99fced43635445c34a116824e38fa01ecede513c7896a6275564ca377f0b5665, {\'signage_point\': SignagePoint(cc_vdf=VDFInfo(challenge=<bytes32: c685f180385ef879e725d63b02d56355dc13beba954d5f9669a52e50def38e43>, number_of_iterations=119382016, output=ClassgroupElement(data=<bytes100: 0200804de0ce0ed1757e0726a3f0e95231366388d949982a0fe730a7b2d1e856d4aab156631e2032b22ba1bb226f25505171e775efe559f8f7dd845b9ccd7140ce275543da50641c49a7b9caf89c810c280db20c393c4423acc6ac9d8d62a79c932a0200>)), cc_proof=VDFProof(witness_type=2, witness=b\'\\x03\\x00D:\\xac\\xe4SDF\\xc90\\x98\\xfdsi{xY4<\\x11\\x8f\\x04Z\\xa6\\xf6\\x93\\xaet\\xdc>\\xa85\\xfa\\xbe\\x99\\xb4\\xd0\\xdbu\\x1c\\x1ei\\xc9\\xab?\\xcc\\xf2\\x92\\xdc$\\xc0,z\\xec\\xdb\\xe6\\x81\\x7f\\x9f\\xf6\\x84\\x8e\\xc6\\xd0B\\xb1\\xdf\\xe0\\xf5\\x16O\\x81\\x11\\xc6^\\x80\\x92\\xea\\xcf\\xbb\\x84\\x1a\\xc2\\xbe\\x91Nq\\x9eM,F\\xbb{.\\xa3\\xb6\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x0c\\x1c\\x00\\xe0\\x01\\x98[\\x07\\xb2\\x8c>\\x0f1\\xbe\\xec!\\xb3\\x12Z\\x94c/B\\x03\\xcd\\xd7\\xf7n\\x82\\xd5\\xe4\\x88W\\x0f8\\x9d\\x03\\x00\\xa5\\xecp\\x16\\xb1\\xde\\xb8\\x93\\xe3A)K\\xbaJ:8\\xd6\\xdd\\xb5\\xbf\\x88GL\\x12KHp\\xa3vQ\\xff\\xe6\\x05\\x83\\xdb%\\x10X\\xeai\\x1f\\xfa\\xff\\x11\\xce\\x0f\\xff_\\xb3.\\x03\\x0cA\\x91W\\xb8\\x98M\\xcdPx\\xccq$|m\\x91\\xc7\\x02]eJ\\t\\x1e\\xd5\\x7f\\x88\\x84"\\xa0\\n\\xdfJ\\xea\\xeb\\xa5\\x9f\\xe5\\xd1\\xf6@\\xa3\\xb8\\x16\\x16/\\x01\\x00\\x00\\x00\\x00\\x00\\x00$T\\x00\\xf7\\xf3I\\xd3\\xf1\\xa4\\x99\\x81MG\\x86 \\x11\\xe6\\x1a\\x1dy\\xbdp\\xf0zV\\xca\\xe6=\\xd3f\\xe0N\\xa4\\x00\\x97\\x0b\\x00\\x00\\xb8\\x06\\xacK\\x07\\xd9YP\\x1f\\xdf\\xe2\\x0bA\\x85\\xbe[\\x0eR\\x0c\\x97\\xa2\\x8f\\xcc\\x91\\xb8L]\\xe2\\xefJ\\x01\\x14t\\xf2\\xf7\\x07\\xbf8\\xfaS\\\\\\xec\\xb2|\\xccE\\xb1E\\xb0\\x8f\\xea\\x9a\\xdc\\xbd\\xb9\\x1fc\\xae\\xce\\x92\\xb2L<R-\\x1c\\xeb\\xe0\\x7f\\x04$T\\x94~gE|\\xdf\\xa8A\\x83\\xdd\\xa5\\xb0,gN\\xea;\\xa7\\x06\\xdfn~\\xe4+\\x01\\x00\', normalized_to_identity=False), rc_vdf=VDFInfo(challenge=<bytes32: 17016f80eb0c631c495af6fc3099897f0d7f86078a32db862c3be8af23a041e3>, number_of_iterations=3571339, output=ClassgroupElement(data=<bytes100: 010066dde86cb1bf8d0945b2996fa9a1488b0390ed2286a0992d33897870d1db6290447f4f603f49f3e9476386d7bc05d0b562eec469655dff8d722f2c24ff259a07b12a0c42702d4db8c5f2bb911c726175b5a577a69d79a34c1354585c16b0100c0100>)), rc_proof=VDFProof(witness_type=2, witness=b"\\x02\\x00\\x10\\x9e\\x8e\\xe3D\\x11gf\\xde[\\xab\\xeaj\\xcfL+(\\xf9\\x80L\\xa6\\xa8^\\x8c\\xd2]]x=AG\\x88\\x1d@\\xd2<2\\xbd\\xd7\\xcf\\x16\\xbe\\xb5K\\xa9\\x92t\\x9d\\xb2+\\xcdP. \\xe4Ws\\xfa\\xe6\\xaco\\x8c\\x00=\\xd9\\xd6\\x95\\x02W5%\\xf17R\\xd6k\\x8a\\xa2q\\xfe\\x15\\x84kB1\\xe45f`\\x08\\x89\\xad\\x04g\\x93\\x08\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x0c\\x1c\\x00\\x89\\x7fB9\\xd0\\xe44I\\xa6\\xdduG\\xe6\\xad\\x95\\x9c\\xc1~\\x80\\x1f\\xac<7\\xe8\\xef\\x8a\\xe6\\xa1l\\x8b\\xa5I\\xc9\\x00\\x00\\xf4\\xc4J\\x10g\\xfa\\xa8\\xa8\\xe1/6\\x89\\xbe\\xff\\xde,J^F\\x02\\xa5\\xf9\\xe1\\x8b\\xa9I A\\x84\\xf8\\xccBls\\xa7v8m\\x8f\\x84]\\xecf\\xbdK\\xf7\\xe7\\xeb\\x95\\xaf^\\xb6>y\\xfe\\x00P\\xe6J\\x04y\\x86q5Y5\\xdcs]\\xba\\x196\\x18\\x8c\\x1e\\x0e\\xca\\x143E\\xca\\x98\\x1c\\xe5\\r\'\\xb7\\xa6\\xaf\\x0f\\xefK\\xa7$\\x16\\x19\\x01\\x00\\x00\\x00\\x00\\x00\\x00$T\\x00\\xd7\\x7fZ\\xef\\xbcl\\xe8\\xe8B\\xe93\\xc1|s\\x9c\\x92\\x99\\xa2;J\\xc3y|\\xca\\x01\\x80\\xc9\\xe9\\x07\\xcc\\x83\\xa3\\xa5\\x00\\x00_\\xc8\\x14\\x12\\xecSt\\xca\\x82\\xbf3\\xf9\\\\3,\\x17\\x05w\\t\\x9b]\\x1f\\xe9\\x19\\xec\\x94o\\xafxP\\xaef\\x08ftuS\\x1b\\x97x<I&\\xcf\\xeb46\\x842Y\\xf6\\xf7\\x87\\xe6\\xc1\\xb1j\\x9f\\x1f\\x95\\x13\\x10\\xe4BY\\xaap`\\x82\\x04\\xf0\\xdc\\xaet\\x1f\\xbf\\xc8\\xac\\xbdu\\xfc_\\x05\\xff\\x01<\\xb17\\xe0?!!7A\\xae[\\x01\\x00", normalized_to_identity=False)), \'time_received\': 1628129744.071252, \'reverted\': True}') 
`
