### ISSUE TITLE
Can explain what means about this code?

### ISSUE THREAD

**Issue by rocqina** [Chia-Network/pool-reference#76]
https://github.com/Chia-Network/chia-blockchain/blob/95296cd7861942b9f8ee1748829d5068c35c81d0/chia/pools/pool_puzzles.py#L229

![image](https://user-images.githubusercontent.com/15166591/122035791-6a638f00-ce05-11eb-9de6-d90420b295f3.png)

**Comment by mariano54** [comment]
It looks for the outputs of the spend of a singleton, and find the outoput with an odd amount. A singleton can only create one output with an odd amount, and that is the new singleton.
