### ISSUE TITLE
Cannot find class SubmitPartial, PoolInfo from chia.protocols.pool_protocol

### ISSUE THREAD

**Issue by truongthihuonggiang** [Chia-Network/pool-reference#8]
I have look at file pool_protocol.py, it doesn't have these class, Submit Partial and PoolInfo. Any help?

**Comment by Gerraweb** [comment]
Duplicate of #1

**Comment by mariano54** [comment]
These are in chia-blockchain. This has not been released yet so we're not providing customer support.
