### ISSUE TITLE
Can give the source about params of pool_list configuration?

### ISSUE THREAD

**Issue by rocqina** [Chia-Network/pool-reference#80]
So if I want a farmer to connect a pool by cli, I have to config pool_list manually in the config.yaml and I can not how to get the values of some params .  Can the official  give the source about the params of pool_list， or how I can use chia cli to get these params。

  - authentication_key_info_signature: 
    authentication_public_key: 
    authentication_public_key_timestamp:
    owner_public_key: 
    target_signature: 
    singleton_genesis:
    target_puzzle_hash:

**Comment by mariano54** [comment]
you need to use the wallet to create a singleton (plot nft), the wallet will then fill the values into the config.
