### ISSUE TITLE
distributed architecture and preparation for higher load

### ISSUE THREAD

**Issue by ppolewicz** [Chia-Network/pool-reference#91]
Hey,

I've been tasked with implementing a production-ready Chia pool for one of my clients (actually may be more than one, demand on chia pools seems to be at an all-time high!), but during review of the code in this repository a pattern quickly emerged. There is a separate object responsible for persistence. By default it uses sqlite, which can only handle a few transactions per second and a real pool could use a different database in place of the sqlite, by implementing PoolStore interface. That got us thinking. What if the implementation of that class didn't really do anything, but instead it would relay all the calls to a REST API backend? Then you could write that backend in whatever programming language you'd like, you could deploy it on a serverless platform, the new cloudflare worker edge computing thing and you could scale the resources for it separately from the pool-reference code.
It would not be a lot of work and it would allow people who use php, java, .net etc to implement pools. I heard that the chia core team would like to have a good ecosystems of pools. Making it more accessible to software developers of the world seems like a step in the right direction.

There are a couple of things that would need to be factored out to the REST API backend that are not in the PoolStore interface, specifically I'm thinking about the difficulty adjustment algorithm... But that's also not a lot of work.

I would like to inquire - would a PR adding (optional) REST API backend architecture be welcome? We'd refactor the PoolStore thing to become an `abc.abcmeta` AbstractPoolBackend, which would only have empty methods describing the interface, and we'd move the current PoolStore to SQLitePoolBackend or SimplePoolBackend or something like that, maintaining the current functionality of the system, just moving the code around a little bit. Finally (in a separate PR), we'd add a RESTPoolBackend or HttpPoolBackend which would use simple rpc-like calls to enable pool logic to be handled by a separate host. Nobody would be forced to use RESTPoolBackend if they didn't want to. People could easily add ZeromqPoolBackend, XMLRPCPoolBackend, ThriftPoolBackend, gRPCPoolBackend and all kinds of things if they wanted to, once our first PR is in (not necessarily making them opensource, but hopefully they'd share it).

We have to get it done one way or another. Fortunately I can make the REST API changes opensource, the only question now is whether I can work within the pool-reference code to make it available to everyone, or is this not the right place for this sort of flexible backend layer?

**Comment by mariano54** [comment]
Hi @ppolewicz! Thank you for your post.

I think that the performance of sqlite is probably sufficient for this use case, up to a pretty large pool size. Sqlite can do many thousands of transactions per second if it is configured properly. Of course this would require some tweaking, since we didn't do any performance testing.

That said, I understand that some people might prefer other databases or solutions. I would be open to looking at a PR, but cannot commit to merging it at this point. Thank you for making your work open source

**Comment by alvaroslm** [comment]
god almighty. serverless madness

**Comment by mpnowacki-reef** [comment]
@mariano54 I've submitted a PR that introduces these changes: https://github.com/Chia-Network/pool-reference/pull/99
