### ISSUE TITLE
Some problem wiht reward calculation 

### ISSUE THREAD

**Issue by neal-zhu** [Chia-Network/pool-reference#92]
Hey,

There is a problem with the current earnings calculation. The program periodically collects all current pool coins, and then divides them equally according to the current point. But in fact, not every point should evenly divide all the benefits. For example, for farmer A, it only submits 1 point in the first block A, and there is no subsequent submission, so its reward should  be 1/#points_of_block_A * 1.75 instead of  1/#points * total_reward

**Comment by mariano54** [comment]
This is customizable. I think the default behavior is reasonable, but you are free to change it.
