### ISSUE TITLE
Missing 0.25 Transactions

### ISSUE THREAD

**Issue by Nico-VanHaaster** [Chia-Network/pool-reference#93]
Since the last round of updates we are no longer seeing the 0.25 transactions being added to the farmers wallet. The 1.75 is still being awarded to the pool however nothing on the farmer wallet. 

Has this changed in anyway?

**Comment by mariano54** [comment]
No, that goes to your original reward target, same as always. Are you checking on the right key?

**Comment by Nico-VanHaaster** [comment]
Yes it is the correct wallet. Here is a list of the transactions below. All of them incoming from the pool wallet.



Type | To | Date | Status | Amount | Fee
-- | -- | -- | -- | -- | --
Incoming | txch15zlytacwvd2g93x424gvlv3fyemu92a6fkrlpdku9uq25skjlj9qk45jck | 06/22/2021 15:17:36 | Confirmed at height 231498 | 0.81528 | 0
Incoming | txch15zlytacwvd2g93x424gvlv3fyemu92a6fkrlpdku9uq25skjlj9qk45jck | 06/22/2021 14:58:57 | Confirmed at height 231431 | 0.962483333 | 0
Outgoing | txch1ju7yrja7dw5klz2826y9r0j0z8j2ntsd50tquevcxgemqydxcefqtwad0z | 06/22/2021 09:18:06 | Confirmed at height 230384 | 10 | 0.0001
Incoming | txch15zlytacwvd2g93x424gvlv3fyemu92a6fkrlpdku9uq25skjlj9qk45jck | 06/22/2021 09:07:00 | Confirmed at height 230346 | 1.73247999991 | 0
Incoming | txch15zlytacwvd2g93x424gvlv3fyemu92a6fkrlpdku9uq25skjlj9qk45jck | 06/22/2021 07:15:54 | Confirmed at height 229953 | 3.4649799999 | 0
Incoming | txch15zlytacwvd2g93x424gvlv3fyemu92a6fkrlpdku9uq25skjlj9qk45jck | 06/22/2021 01:55:37 | Confirmed at height 228838 | 1.73247999995 | 0
Incoming | txch15zlytacwvd2g93x424gvlv3fyemu92a6fkrlpdku9uq25skjlj9qk45jck | 06/22/2021 00:45:57 | Confirmed at height 228570 | 1.73248 | 0
Incoming | txch15zlytacwvd2g93x424gvlv3fyemu92a6fkrlpdku9uq25skjlj9qk45jck | 06/22/2021 00:05:43 | Confirmed at height 228447 | 3.46497999988 | 0
Incoming | txch15zlytacwvd2g93x424gvlv3fyemu92a6fkrlpdku9uq25skjlj9qk45jck | 06/21/2021 22:45:24 | Confirmed at height 228211 | 1.73248 | 0
Incoming | txch15zlytacwvd2g93x424gvlv3fyemu92a6fkrlpdku9uq25skjlj9qk45jck | 06/21/2021 22:07:14 | Confirmed at height 228094 | 1.73247999984 | 0

**Comment by mariano54** [comment]
Can you check your rewards address in the config file? `farmer.xch_target_address`

**Comment by mariano54** [comment]
I have not seen any issues with the 0.25. They should be in your farmer xch target address.
