### ISSUE TITLE
in decode_puzzle hash raise ValueError("Invalid Address")

### ISSUE THREAD

**Issue by yhhwpp** [Chia-Network/pool-reference#94]
i run  "sudo CHIA_ROOT="/your/home/dir/.chia/testnet7" ./venv/bin/python pool/pool_server.py", Throws the following error

![IMG_20210622_183130](https://user-images.githubusercontent.com/7929656/122914877-b5dde600-d38d-11eb-84ad-213c7064eb27.jpg)

Does it mean that the `default_target_address`  in the `config,yaml` file is wrong?

How was this  `default_target_address` generated？

**Comment by mariano54** [comment]
Yes it has to be a chia address
